using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Generators_Design_Vbd;

[Generator(LanguageNames.CSharp)]
public sealed class VbdAccessGenerator : IIncrementalGenerator
{
    private static readonly string[] AccessSuffixes = ["Repository", "Store", "Gateway", "Accessor"];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cls &&
                    cls.Modifiers.Any(SyntaxKind.PublicKeyword) &&
                    !cls.Modifiers.Any(SyntaxKind.StaticKeyword),
                transform: GetModel)
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private VbdVaultModel? GetModel(GeneratorSyntaxContext ctx, System.Threading.CancellationToken cancellationToken)
    {
        if (ctx.Node is not ClassDeclarationSyntax cls) return null;
        if (!AccessSuffixes.Any(s => cls.Identifier.Text.EndsWith(s, System.StringComparison.Ordinal))) return null;
        if (ctx.SemanticModel.GetDeclaredSymbol(cls, cancellationToken) is not INamedTypeSymbol type) return null;

        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString();

        var methods = type.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.DeclaredAccessibility == Accessibility.Public &&
                        m.MethodKind == MethodKind.Ordinary &&
                        !m.IsStatic)
            .Select(m => new VbdMethodModel(
                m.Name,
                m.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                m.Parameters
                    .Select(p => new VbdParameterModel(
                        p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                        p.Name))
                    .ToList()))
            .ToList();

        return new VbdVaultModel(type.Name, ns, "access vault", methods);
    }

    private static void Execute(SourceProductionContext ctx, VbdVaultModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling - VBD Access Vault Generator />");
        sb.AppendLine("// VBD0006: Explicit boundary contract for access vault");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Auto-generated boundary contract for {model.VaultKind} <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public interface I{model.TypeName}");
        sb.AppendLine("{");

        foreach (var method in model.Methods)
        {
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
            sb.AppendLine($"    /// <summary>Boundary contract method mirroring <see cref=\"{model.TypeName}.{method.Name}\"/>.</summary>");
            sb.AppendLine($"    {method.ReturnType} {method.Name}({parameters});");
        }

        sb.AppendLine("}");

        ctx.AddSource($"I{model.TypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record VbdVaultModel(
        string TypeName,
        string Namespace,
        string VaultKind,
        List<VbdMethodModel> Methods);

    private sealed record VbdMethodModel(
        string Name,
        string ReturnType,
        List<VbdParameterModel> Parameters);

    private sealed record VbdParameterModel(string Type, string Name);
}

