using System.Text;

namespace VisionaryCoder.Generators.Design.Vbd;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class VbdManagerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cls &&
                    cls.Modifiers.Any(kind: SyntaxKind.PublicKeyword) &&
                    !cls.Modifiers.Any(kind: SyntaxKind.StaticKeyword) &&
                    cls.Identifier.Text.EndsWith(value: "Manager"),
                transform: GetModel)
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static VbdManagerModel? GetModel(GeneratorSyntaxContext ctx, System.Threading.CancellationToken cancellationToken)
    {
        if (ctx.Node is not ClassDeclarationSyntax cls) return null;
        if (ctx.SemanticModel.GetDeclaredSymbol(declarationSyntax: cls, cancellationToken: cancellationToken) is not INamedTypeSymbol type) return null;

        var ns = type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString();

        var methods = type.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(predicate: m => m.DeclaredAccessibility == Accessibility.Public &&
                                   m.MethodKind == MethodKind.Ordinary &&
                                   !m.IsStatic)
            .Select(selector: m => new VbdMethodModel(
                Name: m.Name,
                ReturnType: m.ReturnType.ToDisplayString(format: SymbolDisplayFormat.MinimallyQualifiedFormat),
                Parameters: m.Parameters
                    .Select(selector: p => new VbdParameterModel(
                        Type: p.Type.ToDisplayString(format: SymbolDisplayFormat.MinimallyQualifiedFormat),
                        Name: p.Name))
                    .ToList()))
            .ToList();

        return new VbdManagerModel(TypeName: type.Name, Namespace: ns, Methods: methods);
    }

    private static void Execute(SourceProductionContext ctx, VbdManagerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling - VBD Manager Vault Generator />");
        sb.AppendLine(value: "// VBD0006: Explicit orchestration contract for manager vault");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(value: model.Namespace))
        {
            sb.AppendLine(value: $"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine(value: $"/// <summary>Auto-generated business-intent contract for manager vault <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"/// <remarks>VBD Manager Vault: policy orchestration and use-case flow boundary.</remarks>");
        sb.AppendLine(value: $"public interface I{model.TypeName}");
        sb.AppendLine(value: "{");

        foreach (var method in model.Methods)
        {
            var parameters = string.Join(separator: ", ", values: method.Parameters.Select(selector: p => $"{p.Type} {p.Name}"));
            sb.AppendLine(value: $"    /// <summary>Orchestration contract method mirroring <see cref=\"{model.TypeName}.{method.Name}\"/>.</summary>");
            sb.AppendLine(value: $"    {method.ReturnType} {method.Name}({parameters});");
        }

        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"I{model.TypeName}.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record VbdManagerModel(
        string TypeName,
        string Namespace,
        List<VbdMethodModel> Methods);

    private sealed record VbdMethodModel(
        string Name,
        string ReturnType,
        List<VbdParameterModel> Parameters);

    private sealed record VbdParameterModel(string Type, string Name);
}

