using System;

namespace VisionaryCoder.Caching
{
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public sealed class GenerateCacheAttribute : System.Attribute { }
}

namespace VisionaryCoder.Resilience
{
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public sealed class GenerateRetryAttribute : System.Attribute
    {
        public int Attempts { get; }
        public GenerateRetryAttribute(int attempts = 3) => Attempts = attempts;
    }
}

namespace VisionaryCoder.Metrics
{
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public sealed class GenerateMetricAttribute : System.Attribute
    {
        public string Name { get; }
        public GenerateMetricAttribute(string name) => Name = name;
    }
}

namespace VisionaryCoder.Auditing
{
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public sealed class GenerateAuditAttribute : System.Attribute { }
}

namespace VisionaryCoder.Serialization
{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public sealed class GenerateSerializerAttribute : System.Attribute { }
}

namespace VisionaryCoder.Errors
{
    [System.AttributeUsage(System.AttributeTargets.Enum)]
    public sealed class GenerateErrorCodesAttribute : System.Attribute { }
}

namespace VisionaryCoder.Localization
{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public sealed class GenerateLocalizationAttribute : System.Attribute { }
}

namespace Vc.Generators.Abstractions;

public abstract class VcGeneratorBase : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
        => context.RegisterForSyntaxNotifications(() => new Receiver(TargetAttributeName));

    protected abstract string TargetAttributeName { get; }
    protected abstract string Category { get; }
    protected abstract string Feature { get; }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not Receiver receiver)
            return;

        foreach (var candidate in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(candidate.SyntaxTree);
            var symbol = model.GetDeclaredSymbol(candidate);
            if (symbol is null)
                continue;

            var source = GenerateSource(symbol);
            var fileName = $"{symbol.Name}_{Feature}.g.cs";
            context.AddSource(fileName, source);
        }
    }

    protected virtual string GenerateSource(ISymbol symbol)
    {
        var ns = symbol.ContainingNamespace?.ToDisplayString() ?? "Global";
        var name = symbol.Name;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace {ns}.Generated.{Category};");
        sb.AppendLine();
        sb.AppendLine($"public static class {name}_{Feature}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string Info => \"{Category}:{Feature} for {name}\";");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class Receiver : ISyntaxReceiver
    {
        private readonly string _attributeName;
        public List<TypeDeclarationSyntax> Candidates { get; } = new();

        public Receiver(string attributeName) => _attributeName = attributeName;

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            if (syntaxNode is TypeDeclarationSyntax t &&
                t.AttributeLists
                 .SelectMany(a => a.Attributes)
                 .Any(a => a.Name.ToString().Contains(_attributeName)))
            {
                Candidates.Add(t);
            }
        }
    }
}

