using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.SecurityGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class JwtSecurityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(EmitJwtService);
    }

    private static void EmitJwtService(IncrementalGeneratorPostInitializationContext ctx)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.SecurityGenerators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IdentityModel.Tokens.Jwt;");
        sb.AppendLine("using System.Security.Claims;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.IdentityModel.Tokens;");
        sb.AppendLine();
        sb.AppendLine("namespace VisionaryCoder.Tooling.Security;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Service interface for JWT token generation and validation.</summary>");
        sb.AppendLine("public interface IJwtTokenService");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Generates a JWT token with the specified claims.</summary>");
        sb.AppendLine("    string GenerateToken(string userId, string email, IEnumerable<string>? roles = null, int expiryMinutes = 60);");
        sb.AppendLine("    /// <summary>Validates a JWT token and returns the claims principal if valid.</summary>");
        sb.AppendLine("    ClaimsPrincipal? ValidateToken(string token);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Auto-generated JWT token service implementation.</summary>");
        sb.AppendLine("public sealed class JwtTokenService : IJwtTokenService");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IConfiguration _config;");
        sb.AppendLine();
        sb.AppendLine("    public JwtTokenService(IConfiguration config) => _config = config;");
        sb.AppendLine();
        sb.AppendLine("    public string GenerateToken(string userId, string email, IEnumerable<string>? roles = null, int expiryMinutes = 60)");
        sb.AppendLine("    {");
        sb.AppendLine("        var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config[\"Jwt:SecretKey\"]!));");
        sb.AppendLine("        var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);");
        sb.AppendLine("        var claims = new List<Claim>");
        sb.AppendLine("        {");
        sb.AppendLine("            new(JwtRegisteredClaimNames.Sub, userId),");
        sb.AppendLine("            new(JwtRegisteredClaimNames.Email, email),");
        sb.AppendLine("            new(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString())");
        sb.AppendLine("        };");
        sb.AppendLine("        if (roles is not null)");
        sb.AppendLine("            foreach (var role in roles)");
        sb.AppendLine("                claims.Add(new Claim(ClaimTypes.Role, role));");
        sb.AppendLine();
        sb.AppendLine("        var token = new JwtSecurityToken(");
        sb.AppendLine("            issuer: _config[\"Jwt:Issuer\"],");
        sb.AppendLine("            audience: _config[\"Jwt:Audience\"],");
        sb.AppendLine("            claims: claims,");
        sb.AppendLine("            expires: DateTime.UtcNow.AddMinutes(expiryMinutes),");
        sb.AppendLine("            signingCredentials: creds);");
        sb.AppendLine();
        sb.AppendLine("        return new JwtSecurityTokenHandler().WriteToken(token);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public ClaimsPrincipal? ValidateToken(string token)");
        sb.AppendLine("    {");
        sb.AppendLine("        var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config[\"Jwt:SecretKey\"]!));");
        sb.AppendLine("        var handler = new JwtSecurityTokenHandler();");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            return handler.ValidateToken(token, new TokenValidationParameters");
        sb.AppendLine("            {");
        sb.AppendLine("                ValidateIssuer = true,");
        sb.AppendLine("                ValidateAudience = true,");
        sb.AppendLine("                ValidIssuer = _config[\"Jwt:Issuer\"],");
        sb.AppendLine("                ValidAudience = _config[\"Jwt:Audience\"],");
        sb.AppendLine("                IssuerSigningKey = key,");
        sb.AppendLine("                ClockSkew = TimeSpan.FromMinutes(1)");
        sb.AppendLine("            }, out _);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch { return null; }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public static class SecurityServiceExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddVisionaryCoderSecurity(this IServiceCollection services, IConfiguration config)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddSingleton<IJwtTokenService, JwtTokenService>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("JwtTokenService.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}