using System.Text;

namespace VisionaryCoder.Generators.Security;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class JwtSecurityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(callback: EmitJwtService);
    }

    private static void EmitJwtService(IncrementalGeneratorPostInitializationContext ctx)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.SecurityGenerators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: "using System;");
        sb.AppendLine(value: "using System.Collections.Generic;");
        sb.AppendLine(value: "using System.IdentityModel.Tokens.Jwt;");
        sb.AppendLine(value: "using System.Security.Claims;");
        sb.AppendLine(value: "using System.Text;");
        sb.AppendLine(value: "using Microsoft.Extensions.Configuration;");
        sb.AppendLine(value: "using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine(value: "using Microsoft.IdentityModel.Tokens;");
        sb.AppendLine();
        sb.AppendLine(value: "namespace VisionaryCoder.Tooling.Security;");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>Service interface for JWT token generation and validation.</summary>");
        sb.AppendLine(value: "public interface IJwtTokenService");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Generates a JWT token with the specified claims.</summary>");
        sb.AppendLine(value: "    string GenerateToken(string userId, string email, IEnumerable<string>? roles = null, int expiryMinutes = 60);");
        sb.AppendLine(value: "    /// <summary>Validates a JWT token and returns the claims principal if valid.</summary>");
        sb.AppendLine(value: "    ClaimsPrincipal? ValidateToken(string token);");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>Auto-generated JWT token service implementation.</summary>");
        sb.AppendLine(value: "public sealed class JwtTokenService : IJwtTokenService");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    private readonly IConfiguration _config;");
        sb.AppendLine();
        sb.AppendLine(value: "    public JwtTokenService(IConfiguration config) => _config = config;");
        sb.AppendLine();
        sb.AppendLine(value: "    public string GenerateToken(string userId, string email, IEnumerable<string>? roles = null, int expiryMinutes = 60)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config[\"Jwt:SecretKey\"]!));");
        sb.AppendLine(value: "        var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);");
        sb.AppendLine(value: "        var claims = new List<Claim>");
        sb.AppendLine(value: "        {");
        sb.AppendLine(value: "            new(JwtRegisteredClaimNames.Sub, userId),");
        sb.AppendLine(value: "            new(JwtRegisteredClaimNames.Email, email),");
        sb.AppendLine(value: "            new(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString())");
        sb.AppendLine(value: "        };");
        sb.AppendLine(value: "        if (roles is not null)");
        sb.AppendLine(value: "            foreach (var role in roles)");
        sb.AppendLine(value: "                claims.Add(new Claim(ClaimTypes.Role, role));");
        sb.AppendLine();
        sb.AppendLine(value: "        var token = new JwtSecurityToken(");
        sb.AppendLine(value: "            issuer: _config[\"Jwt:Issuer\"],");
        sb.AppendLine(value: "            audience: _config[\"Jwt:Audience\"],");
        sb.AppendLine(value: "            claims: claims,");
        sb.AppendLine(value: "            expires: DateTime.UtcNow.AddMinutes(expiryMinutes),");
        sb.AppendLine(value: "            signingCredentials: creds);");
        sb.AppendLine();
        sb.AppendLine(value: "        return new JwtSecurityTokenHandler().WriteToken(token);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    public ClaimsPrincipal? ValidateToken(string token)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config[\"Jwt:SecretKey\"]!));");
        sb.AppendLine(value: "        var handler = new JwtSecurityTokenHandler();");
        sb.AppendLine(value: "        try");
        sb.AppendLine(value: "        {");
        sb.AppendLine(value: "            return handler.ValidateToken(token, new TokenValidationParameters");
        sb.AppendLine(value: "            {");
        sb.AppendLine(value: "                ValidateIssuer = true,");
        sb.AppendLine(value: "                ValidateAudience = true,");
        sb.AppendLine(value: "                ValidIssuer = _config[\"Jwt:Issuer\"],");
        sb.AppendLine(value: "                ValidAudience = _config[\"Jwt:Audience\"],");
        sb.AppendLine(value: "                IssuerSigningKey = key,");
        sb.AppendLine(value: "                ClockSkew = TimeSpan.FromMinutes(1)");
        sb.AppendLine(value: "            }, out _);");
        sb.AppendLine(value: "        }");
        sb.AppendLine(value: "        catch { return null; }");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "public static class SecurityServiceExtensions");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    public static IServiceCollection AddVisionaryCoderSecurity(this IServiceCollection services, IConfiguration config)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        services.AddSingleton<IJwtTokenService, JwtTokenService>();");
        sb.AppendLine(value: "        return services;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: "JwtTokenService.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }
}