using System.Text;

namespace VisionaryCoder.Generators.Security;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class PermissionsGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.PermissionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static PermissionsModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[index: 0];
        var permissionName = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? typeSymbol.Name;
        return new PermissionsModel(TypeName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString(), PermissionName: permissionName);
    }

    private static void Execute(SourceProductionContext ctx, PermissionsModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>RBAC Permission constants</summary>");
        sb.AppendLine(value: $"public static class {model.PermissionName}Permissions");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    public const string {model.PermissionName} = \"{model.PermissionName}\";");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>Policy registration extensions</summary>");
        sb.AppendLine(value: $"public static class {model.PermissionName}PolicyExtensions");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    public static AuthorizationPolicyBuilder Require" + $"{model.PermissionName}(");
        sb.AppendLine(value: "        this AuthorizationPolicyBuilder builder)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: $"        return builder.RequireClaim(\"permission\", {model.PermissionName}Permissions.{model.PermissionName});");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.PermissionName}Permissions.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record PermissionsModel(string TypeName, string Namespace, string PermissionName);
}
