using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class PermissionsGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.PermissionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static PermissionsModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[0];
        var permissionName = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? typeSymbol.Name;
        return new PermissionsModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), permissionName);
    }

    private static void Execute(SourceProductionContext ctx, PermissionsModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>RBAC Permission constants</summary>");
        sb.AppendLine($"public static class {model.PermissionName}Permissions");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string {model.PermissionName} = \"{model.PermissionName}\";");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Policy registration extensions</summary>");
        sb.AppendLine($"public static class {model.PermissionName}PolicyExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static AuthorizationPolicyBuilder Require" + $"{model.PermissionName}(");
        sb.AppendLine("        this AuthorizationPolicyBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return builder.RequireClaim(\"permission\", {model.PermissionName}Permissions.{model.PermissionName});");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.PermissionName}Permissions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record PermissionsModel(string TypeName, string Namespace, string PermissionName);
}
