// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Vc.Generators.Common.Builders;
using Vc.Generators.Common.Diagnostics;
using Vc.Generators.Common.Extensions;

namespace Vc.Generators.Security;

[Generator(LanguageNames.CSharp)]
public sealed class VcSecurityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax or MethodDeclarationSyntax && ((BaseTypeDeclarationSyntax)node).AttributeLists.Count > 0,
                static (ctx, ct) => Transform(ctx, ct))
            .Where(static m => m is not null)!;

        var compilationAndModels = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndModels, static (spc, pair) =>
        {
            var (compilation, models) = pair;
            if (models.IsDefaultOrEmpty)
            {
                return;
            }

            // Group by permission group to avoid duplication
            var grouped = models
                .Where(m => !string.IsNullOrWhiteSpace(m!.GroupName))
                .Cast<SecurityModel>()
                .GroupBy(m => (m.Namespace, m.GroupName), StringComparer.OrdinalIgnoreCase);

            foreach (var group in grouped)
            {
                EmitPermissionCatalog(spc, group.Key.Namespace, group.Key.GroupName, group.SelectMany(m => m.Permissions));
                EmitAuthorizationPolicies(spc, group.Key.Namespace, group.Key.GroupName, group.SelectMany(m => m.Permissions));
                EmitSecurityGuards(spc, group.Key.Namespace, group.Key.GroupName, group.SelectMany(m => m.Permissions));
            }
        });
    }

    private static SecurityModel? Transform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (context.Node is ClassDeclarationSyntax classDecl)
        {
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
            if (symbol is null)
            {
                return null;
            }

            if (!symbol.HasAttribute("PermissionGroupAttribute") &&
                !symbol.HasAttribute("PermissionGroup"))
            {
                return null;
            }

            var ns = symbol.ContainingNamespace?.ToDisplayString() ?? string.Empty;
            var groupAttr = symbol.GetAttribute("PermissionGroupAttribute") ?? symbol.GetAttribute("PermissionGroup");
            var groupName = groupAttr?.ConstructorArguments.Length > 0
                ? groupAttr.Value.ConstructorArguments[0].Value as string
                : symbol.Name;

            var permissions = ImmutableArray.CreateBuilder<PermissionModel>();
            var roles = ImmutableArray.CreateBuilder<RoleRequirementModel>();

            // Methods with [Secure] inside the group
            foreach (var member in symbol.GetMembers().OfType<IMethodSymbol>())
            {
                AddSecurityFromMethod(member, groupName!, permissions, roles);
            }

            return new SecurityModel(
                Namespace: ns,
                GroupName: groupName ?? symbol.Name,
                Permissions: permissions.ToImmutable(),
                Roles: roles.ToImmutable());
        }

        if (context.Node is MethodDeclarationSyntax methodDecl)
        {
            var symbol = context.SemanticModel.GetDeclaredSymbol(methodDecl, ct) as IMethodSymbol;
            if (symbol is null)
            {
                return null;
            }

            if (!symbol.HasAttribute("SecureAttribute") &&
                !symbol.HasAttribute("Secure"))
            {
                return null;
            }

            var ns = symbol.ContainingNamespace?.ToDisplayString() ?? string.Empty;
            var groupName = symbol.ContainingType?.Name ?? "DefaultSecurity";

            var permissions = ImmutableArray.CreateBuilder<PermissionModel>();
            var roles = ImmutableArray.CreateBuilder<RoleRequirementModel>();

            AddSecurityFromMethod(symbol, groupName, permissions, roles);

            return new SecurityModel(
                Namespace: ns,
                GroupName: groupName,
                Permissions: permissions.ToImmutable(),
                Roles: roles.ToImmutable());
        }

        return null;
    }

    private static void AddSecurityFromMethod(
        IMethodSymbol method,
        string groupName,
        ImmutableArray<PermissionModel>.Builder permissions,
        ImmutableArray<RoleRequirementModel>.Builder roles)
    {
        var secureAttr = method.GetAttribute("SecureAttribute") ?? method.GetAttribute("Secure");
        if (secureAttr is null || secureAttr.Value.ConstructorArguments.Length == 0)
        {
            return;
        }

        var permissionName = secureAttr.Value.ConstructorArguments[0].Value as string;
        if (string.IsNullOrWhiteSpace(permissionName))
        {
            return;
        }

        permissions.Add(new PermissionModel(
            GroupName: groupName,
            PermissionName: permissionName!,
            MethodName: method.Name));

        foreach (var roleAttr in method.GetAttributes("RequiresRoleAttribute", "RequiresRole"))
        {
            if (roleAttr.ConstructorArguments.Length == 0)
            {
                continue;
            }

            var roleName = roleAttr.ConstructorArguments[0].Value as string;
            if (string.IsNullOrWhiteSpace(roleName))
            {
                continue;
            }

            roles.Add(new RoleRequirementModel(
                PermissionName: permissionName!,
                RoleName: roleName!));
        }
    }

    private static void EmitPermissionCatalog(
        SourceProductionContext context,
        string ns,
        string groupName,
        IEnumerable<PermissionModel> permissions)
    {
        var distinctPermissions = permissions
            .GroupBy(p => p.PermissionName, StringComparer.OrdinalIgnoreCase)
            .Select(g => g.First())
            .OrderBy(p => p.PermissionName, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (distinctPermissions.Length == 0)
        {
            return;
        }

        var className = $"{groupName}Permissions";
        var fileName = $"{className}.g.cs";

        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("namespace Vc.Generated.Security;");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.Indent();

        foreach (var permission in distinctPermissions)
        {
            var constName = ToIdentifier(permission.PermissionName);
            sb.AppendLine($"public const string {constName} = \"{permission.PermissionName}\";");
        }

        sb.Unindent();
        sb.AppendLine("}");

        context.AddSource(fileName, SourceText.From(sb.ToString(), System.Text.Encoding.UTF8));
    }

    private static void EmitAuthorizationPolicies(
        SourceProductionContext context,
        string ns,
        string groupName,
        IEnumerable<PermissionModel> permissions)
    {
        var distinctPermissions = permissions
            .GroupBy(p => p.PermissionName, StringComparer.OrdinalIgnoreCase)
            .Select(g => g.First())
            .OrderBy(p => p.PermissionName, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (distinctPermissions.Length == 0)
        {
            return;
        }

        var className = $"{groupName}AuthorizationExtensions";
        var fileName = $"{className}.g.cs";

        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine();
        sb.AppendLine("namespace Vc.Generated.Security;");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.Indent();

        sb.AppendLine("public static IServiceCollection AddGenerated" + groupName + "Authorization(this IServiceCollection services)");
        sb.AppendLine("{");
        sb.Indent();
        sb.AppendLine("services.AddAuthorization(options =>");
        sb.AppendLine("{");
        sb.Indent();

        foreach (var permission in distinctPermissions)
        {
            var constName = ToIdentifier(permission.PermissionName);
            sb.AppendLine($"options.AddPolicy({groupName}Permissions.{constName}, p => p.RequireClaim(\"permission\", {groupName}Permissions.{constName}));");
        }

        sb.Unindent();
        sb.AppendLine("});");
        sb.AppendLine();
        sb.AppendLine("return services;");
        sb.Unindent();
        sb.AppendLine("}");

        sb.Unindent();
        sb.AppendLine("}");

        context.AddSource(fileName, SourceText.From(sb.ToString(), System.Text.Encoding.UTF8));
    }

    private static void EmitSecurityGuards(
        SourceProductionContext context,
        string ns,
        string groupName,
        IEnumerable<PermissionModel> permissions)
    {
        var distinctPermissions = permissions
            .GroupBy(p => p.PermissionName, StringComparer.OrdinalIgnoreCase)
            .Select(g => g.First())
            .OrderBy(p => p.PermissionName, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (distinctPermissions.Length == 0)
        {
            return;
        }

        var className = $"{groupName}SecurityGuards";
        var fileName = $"{className}.g.cs";

        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Security.Claims;");
        sb.AppendLine();
        sb.AppendLine("namespace Vc.Generated.Security;");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.Indent();

        foreach (var permission in distinctPermissions)
        {
            var constName = ToIdentifier(permission.PermissionName);
            var methodName = $"Guard_{constName}";

            sb.AppendLine($"public static async System.Threading.Tasks.Task<T> {methodName}<T>(");
            sb.AppendLine("    ClaimsPrincipal user,");
            sb.AppendLine("    System.Func<System.Threading.Tasks.Task<T>> action)");
            sb.AppendLine("{");
            sb.Indent();
            sb.AppendLine($"if (!user.HasClaim(\"permission\", {groupName}Permissions.{constName}))");
            sb.AppendLine("{");
            sb.Indent();
            sb.AppendLine($"throw new System.UnauthorizedAccessException(\"Missing permission {permission.PermissionName}\");");
            sb.Unindent();
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("return await action().ConfigureAwait(false);");
            sb.Unindent();
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.Unindent();
        sb.AppendLine("}");

        context.AddSource(fileName, SourceText.From(sb.ToString(), System.Text.Encoding.UTF8));
    }

    private static string ToIdentifier(string permission)
    {
        // Orders.Read -> Orders_Read
        var chars = permission.Select(c =>
            char.IsLetterOrDigit(c) ? c : '_').ToArray();
        var id = new string(chars);

        if (SyntaxFacts.IsKeywordKind(SyntaxFacts.GetKeywordKind(id)))
        {
            id = "@" + id;
        }

        return id;
    }

    private sealed record PermissionModel(
        string GroupName,
        string PermissionName,
        string MethodName);

    private sealed record RoleRequirementModel(
        string PermissionName,
        string RoleName);

    private sealed record SecurityModel(
        string Namespace,
        string GroupName,
        ImmutableArray<PermissionModel> Permissions,
        ImmutableArray<RoleRequirementModel> Roles);
}
