using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class GraphQLTypeGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.GraphQLTypeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static GraphQLTypeModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new GraphQLTypeModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, GraphQLTypeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("// Note: Requires HotChocolate NuGet package");
        sb.AppendLine("// using HotChocolate.Types;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated GraphQL type configuration for <see cref=\"{{model.TypeName}}\"/>.</summary>");
        sb.AppendLine($"public sealed class {model.TypeName}Type // : ObjectType<{model.TypeName}>");
        sb.AppendLine("{");
        sb.AppendLine("    // TODO: Add field configurations");
        sb.AppendLine("    // protected override void Configure(IObjectTypeDescriptor<" + $"{model.TypeName}> descriptor)");
        sb.AppendLine("    // {");
        sb.AppendLine("    //     descriptor.Field(x => x.PropertyName)");
        sb.AppendLine("    //         .Description(\"Property description\");");
        sb.AppendLine("    // }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}Type.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record GraphQLTypeModel(string TypeName, string Namespace);
}
