using System.Text;

namespace VisionaryCoder.Generators.Distributed;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class GraphQLTypeGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.GraphQLTypeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static GraphQLTypeModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new GraphQLTypeModel(TypeName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, GraphQLTypeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: "// Note: Requires HotChocolate NuGet package");
        sb.AppendLine(value: "// using HotChocolate.Types;");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated GraphQL type configuration for <see cref=\"{{model.TypeName}}\"/>.</summary>");
        sb.AppendLine(value: $"public sealed class {model.TypeName}Type // : ObjectType<{model.TypeName}>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    // TODO: Add field configurations");
        sb.AppendLine(value: "    // protected override void Configure(IObjectTypeDescriptor<" + $"{model.TypeName}> descriptor)");
        sb.AppendLine(value: "    // {");
        sb.AppendLine(value: "    //     descriptor.Field(x => x.PropertyName)");
        sb.AppendLine(value: "    //         .Description(\"Property description\");");
        sb.AppendLine(value: "    // }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.TypeName}Type.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record GraphQLTypeModel(string TypeName, string Namespace);
}
