using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class MessageContractGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.MessageContractAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static MessageContractModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new MessageContractModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, MessageContractModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public sealed record MessageEnvelope<TMessage>");
        sb.AppendLine("{");
        sb.AppendLine("    public required TMessage Message { get; init; }");
        sb.AppendLine("    public required Guid MessageId { get; init; }");
        sb.AppendLine("    public required Guid CorrelationId { get; init; }");
        sb.AppendLine("    public required Guid CausationId { get; init; }");
        sb.AppendLine("    public required DateTimeOffset Timestamp { get; init; }");
        sb.AppendLine("    public required string ContentType { get; init; }");
        sb.AppendLine();
        sb.AppendLine($"    public static MessageEnvelope<TMessage> Create(TMessage message, Guid correlationId = default, Guid causationId = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return new MessageEnvelope<TMessage>");
        sb.AppendLine("        {");
        sb.AppendLine("            Message = message,");
        sb.AppendLine("            MessageId = Guid.NewGuid(),");
        sb.AppendLine("            CorrelationId = correlationId == default ? Guid.NewGuid() : correlationId,");
        sb.AppendLine("            CausationId = causationId == default ? Guid.NewGuid() : causationId,");
        sb.AppendLine("            Timestamp = DateTimeOffset.UtcNow,");
        sb.AppendLine("            ContentType = \"application/json\"");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // TODO: Add serialization helpers (ToJson, FromJson)");
        sb.AppendLine("}");

        ctx.AddSource($"MessageEnvelope.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record MessageContractModel(string MessageType, string Namespace);
}
