using System.Text;

namespace VisionaryCoder.Generators.Distributed;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class OpenApiGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.OpenApiClientAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static OpenApiModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[index: 0];
        var specPath = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "openapi.json";
        var clientName = attr.ConstructorArguments.Length > 1 ? attr.ConstructorArguments[index: 1].Value?.ToString() ?? typeSymbol.Name : typeSymbol.Name;
        return new OpenApiModel(InterfaceName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString(), SpecPath: specPath, ClientName: clientName);
    }

    private static void Execute(SourceProductionContext ctx, OpenApiModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "// OpenAPI spec: " + model.SpecPath);
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>Generated from OpenAPI specification</summary>");
        sb.AppendLine(value: $"public sealed class {model.ClientName}Client");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    private readonly HttpClient _httpClient;");
        sb.AppendLine();
        sb.AppendLine(value: $"    public {model.ClientName}Client(HttpClient httpClient)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    // TODO: Generated endpoint methods from OpenAPI spec");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.ClientName}Client.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record OpenApiModel(string InterfaceName, string Namespace, string SpecPath, string ClientName);
}
