using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class OpenApiGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.OpenApiClientAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static OpenApiModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[0];
        var specPath = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "openapi.json";
        var clientName = attr.ConstructorArguments.Length > 1 ? attr.ConstructorArguments[1].Value?.ToString() ?? typeSymbol.Name : typeSymbol.Name;
        return new OpenApiModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), specPath, clientName);
    }

    private static void Execute(SourceProductionContext ctx, OpenApiModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("// OpenAPI spec: " + model.SpecPath);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated from OpenAPI specification</summary>");
        sb.AppendLine($"public sealed class {model.ClientName}Client");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine();
        sb.AppendLine($"    public {model.ClientName}Client(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // TODO: Generated endpoint methods from OpenAPI spec");
        sb.AppendLine("}");

        ctx.AddSource($"{model.ClientName}Client.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record OpenApiModel(string InterfaceName, string Namespace, string SpecPath, string ClientName);
}
