using System.Text;

namespace VisionaryCoder.Generators.Distributed;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class OutboxGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Distributed.VcOutboxAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static OutboxModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
        return new OutboxModel(TypeName: typeSymbol.Name, Namespace: ns);
    }

    private static void Execute(SourceProductionContext ctx, OutboxModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: "using System;");
        sb.AppendLine(value: "using System.Collections.Generic;");
        sb.AppendLine(value: "using System.Threading;");
        sb.AppendLine(value: "using System.Threading.Tasks;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(value: model.Namespace))
        {
            sb.AppendLine(value: $"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine(value: $"/// <summary>Auto-generated outbox message entry for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"public sealed record {model.TypeName}OutboxEntry(");
        sb.AppendLine(value: "    Guid Id,");
        sb.AppendLine(value: "    string MessageType,");
        sb.AppendLine(value: "    string Payload,");
        sb.AppendLine(value: "    DateTimeOffset OccurredAt,");
        sb.AppendLine(value: "    DateTimeOffset? ProcessedAt);");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated outbox repository contract for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"public interface I{model.TypeName}OutboxRepository");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    Task AddAsync({model.TypeName}OutboxEntry entry, CancellationToken cancellationToken = default);");
        sb.AppendLine(value: $"    Task<IReadOnlyList<{model.TypeName}OutboxEntry>> GetPendingAsync(int maxCount, CancellationToken cancellationToken = default);");
        sb.AppendLine(value: $"    Task MarkProcessedAsync(Guid id, CancellationToken cancellationToken = default);");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated outbox dispatcher contract for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"public interface I{model.TypeName}OutboxDispatcher");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    Task DispatchPendingAsync(CancellationToken cancellationToken = default);");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.TypeName}Outbox.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record OutboxModel(string TypeName, string Namespace);
}
