using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class OutboxGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Distributed.VcOutboxAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static OutboxModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
        return new OutboxModel(typeSymbol.Name, ns);
    }

    private static void Execute(SourceProductionContext ctx, OutboxModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Auto-generated outbox message entry for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public sealed record {model.TypeName}OutboxEntry(");
        sb.AppendLine("    Guid Id,");
        sb.AppendLine("    string MessageType,");
        sb.AppendLine("    string Payload,");
        sb.AppendLine("    DateTimeOffset OccurredAt,");
        sb.AppendLine("    DateTimeOffset? ProcessedAt);");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated outbox repository contract for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public interface I{model.TypeName}OutboxRepository");
        sb.AppendLine("{");
        sb.AppendLine($"    Task AddAsync({model.TypeName}OutboxEntry entry, CancellationToken cancellationToken = default);");
        sb.AppendLine($"    Task<IReadOnlyList<{model.TypeName}OutboxEntry>> GetPendingAsync(int maxCount, CancellationToken cancellationToken = default);");
        sb.AppendLine($"    Task MarkProcessedAsync(Guid id, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated outbox dispatcher contract for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public interface I{model.TypeName}OutboxDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    Task DispatchPendingAsync(CancellationToken cancellationToken = default);");
        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}Outbox.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record OutboxModel(string TypeName, string Namespace);
}
