using System.Text;  

namespace VisionaryCoder.Generators.Api;

[Generator(LanguageNames.CSharp)]
public sealed class ApiClientGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.ApiClientAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static ApiClientModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[0];
        var clientName = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? typeSymbol.Name;
        return new ApiClientModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), clientName);
    }

    private static void Execute(SourceProductionContext ctx, ApiClientModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated API client implementation for <see cref=\"I{model.InterfaceName}\"/>.</summary>");
        sb.AppendLine($"public sealed class {model.ClientName}Client : I{model.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine();
        sb.AppendLine($"    public {model.ClientName}Client(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // TODO: Implement endpoint methods");
        sb.AppendLine();
        sb.AppendLine("    partial void OnBeforeRequest(HttpRequestMessage request);");
        sb.AppendLine("    partial void OnAfterResponse(HttpResponseMessage response);");
        sb.AppendLine("}");

        ctx.AddSource($"{model.ClientName}Client.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record ApiClientModel(string InterfaceName, string Namespace, string ClientName);
}
