using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class HttpEndpointGenerator : IIncrementalGenerator
{
    private const string GetAttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.HttpGetAttribute";
    private const string PostAttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.HttpPostAttribute";
    private const string PutAttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.HttpPutAttribute";
    private const string DeleteAttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.HttpDeleteAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var getProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GetAttributeFullName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx, "GET"))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(getProvider, Execute);
    }

    private static EndpointModel? GetModel(GeneratorAttributeSyntaxContext ctx, string method)
    {
        if (ctx.TargetSymbol is not IMethodSymbol methodSymbol) return null;
        var route = ctx.Attributes[0].ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "/api/endpoint";
        return new EndpointModel(methodSymbol.Name, methodSymbol.ContainingType.Name, methodSymbol.ContainingNamespace.ToDisplayString(), method, route);
    }

    private static void Execute(SourceProductionContext ctx, EndpointModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Minimal API endpoint registration</summary>");
        sb.AppendLine("public static class " + $"{model.TypeName}Endpoints");
        sb.AppendLine("{");
        sb.AppendLine($"    public static void Map{model.MethodName}Endpoint(this IEndpointRouteBuilder app)");
        sb.AppendLine("    {");
        sb.AppendLine($"        app.MapMethods(\"{model.Route}\", new[] {{ \"{model.HttpMethod}\" }}, Handle)");
        sb.AppendLine("            .WithName(\"" + $"{model.MethodName}\")");
        sb.AppendLine("            .WithOpenApi();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static IResult Handle(HttpContext context) => Results.Ok(\"Not Implemented\");");
        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}Endpoints.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record EndpointModel(string MethodName, string TypeName, string Namespace, string HttpMethod, string Route);
}
