using System.Text;

namespace Vc.Generators.Common.Builders;

file sealed class IndentedStringBuilder
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    public void Indent()
    {
        _indent++;
    }

    public void Unindent()
    {
        _indent = Math.Max(0, _indent - 1);
    }

    public void AppendLine(string text = "")
    {
        if (text.Length > 0)
            _sb.Append(' ', _indent * 4);
        _sb.AppendLine(text);
    }
    public override string ToString()
    {
        return _sb.ToString();
    }
}

sealed class SourceBuilder(StringBuilder sb)
{
    public void Line(string text = "")
    {
        sb.AppendLine(text);
    }

    public void Raw(string text)
    {
        sb.Append(text);
    }

    public override string ToString()
    {
        return sb.ToString();
    }
}

public sealed class FileBuilder
{
    private readonly SourceBuilder _sb = new SourceBuilder(new StringBuilder());

    public FileBuilder Header()
    {
        _sb.Line("// <auto-generated />");
        return this;
    }

    public FileBuilder Namespace(string ns)
    {
        _sb.Line($"namespace {ns};");
        _sb.Line();
        return this;
    }

    public FileBuilder Line(string text = "")
    {
        _sb.Line(text);
        return this;
    }

    public override string ToString()
    {
        return _sb.ToString();
    }
}