using System.Text;

namespace VisionaryCoder.Generators.Resilience;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class ConfigurationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.ConfigSectionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static ConfigurationModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[index: 0];
        var sectionName = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? typeSymbol.Name;
        return new ConfigurationModel(ConfigType: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString(), SectionName: sectionName);
    }

    private static void Execute(SourceProductionContext ctx, ConfigurationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>Extension method to register " + $"{model.ConfigType} configuration</summary>");
        sb.AppendLine(value: $"public static class {model.ConfigType}ConfigurationExtensions");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    public static IServiceCollection Add{model.ConfigType}Configuration(");
        sb.AppendLine(value: "        this IServiceCollection services,");
        sb.AppendLine(value: "        IConfiguration configuration)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: $"        var section = configuration.GetSection(\"{model.SectionName}\");");
        sb.AppendLine(value: $"        services.Configure<{model.ConfigType}>(section);");
        sb.AppendLine(value: $"        // TODO: Add validation using FluentValidation or similar");
        sb.AppendLine(value: "        return services;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.ConfigType}ConfigurationExtensions.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record ConfigurationModel(string ConfigType, string Namespace, string SectionName);
}
