using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ConfigurationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.ConfigSectionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static ConfigurationModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[0];
        var sectionName = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? typeSymbol.Name;
        return new ConfigurationModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), sectionName);
    }

    private static void Execute(SourceProductionContext ctx, ConfigurationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Extension method to register " + $"{model.ConfigType} configuration</summary>");
        sb.AppendLine($"public static class {model.ConfigType}ConfigurationExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection Add{model.ConfigType}Configuration(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        IConfiguration configuration)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var section = configuration.GetSection(\"{model.SectionName}\");");
        sb.AppendLine($"        services.Configure<{model.ConfigType}>(section);");
        sb.AppendLine($"        // TODO: Add validation using FluentValidation or similar");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.ConfigType}ConfigurationExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record ConfigurationModel(string ConfigType, string Namespace, string SectionName);
}
