using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class FeatureFlagGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.FeatureFlagAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static FeatureFlagModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[0];
        var flagName = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? typeSymbol.Name;
        return new FeatureFlagModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), flagName);
    }

    private static void Execute(SourceProductionContext ctx, FeatureFlagModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated feature flag configuration for {model.FlagName}.</summary>");
        sb.AppendLine($"public sealed class {model.FlagName}FeatureFlags");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string FlagName = \"{model.FlagName}\";");
        sb.AppendLine();
        sb.AppendLine("    public bool IsEnabled { get; private set; }");
        sb.AppendLine();
        sb.AppendLine("    public static bool IsEnabled(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Integrate with IFeatureManager or similar");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.FlagName}FeatureFlags.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record FeatureFlagModel(string TypeName, string Namespace, string FlagName);
}
