using System.Text;

namespace VisionaryCoder.Generators.Resilience;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class FeatureFlagGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.FeatureFlagAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static FeatureFlagModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[index: 0];
        var flagName = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? typeSymbol.Name;
        return new FeatureFlagModel(TypeName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString(), FlagName: flagName);
    }

    private static void Execute(SourceProductionContext ctx, FeatureFlagModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated feature flag configuration for {model.FlagName}.</summary>");
        sb.AppendLine(value: $"public sealed class {model.FlagName}FeatureFlags");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    public const string FlagName = \"{model.FlagName}\";");
        sb.AppendLine();
        sb.AppendLine(value: "    public bool IsEnabled { get; private set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    public static bool IsEnabled(IServiceProvider serviceProvider)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        // TODO: Integrate with IFeatureManager or similar");
        sb.AppendLine(value: "        return false;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.FlagName}FeatureFlags.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record FeatureFlagModel(string TypeName, string Namespace, string FlagName);
}
