using System.Text;

namespace VisionaryCoder.Generators.Resilience;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class RetryPolicyGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Resilience.VcRetryPolicyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static RetryPolicyModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
        return new RetryPolicyModel(TypeName: typeSymbol.Name, Namespace: ns);
    }

    private static void Execute(SourceProductionContext ctx, RetryPolicyModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(value: model.Namespace))
        {
            sb.AppendLine(value: $"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine(value: $"/// <summary>Auto-generated retry policy settings for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"public static class {model.TypeName}RetrySettings");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Maximum number of retry attempts before failing.</summary>");
        sb.AppendLine(value: "    public const int MaxAttempts = 3;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Base delay between retry attempts in seconds.</summary>");
        sb.AppendLine(value: "    public const double BaseDelaySeconds = 1.0;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Maximum delay cap between retry attempts in seconds.</summary>");
        sb.AppendLine(value: "    public const double MaxDelaySeconds = 30.0;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Whether to use exponential backoff between retries.</summary>");
        sb.AppendLine(value: "    public const bool UseExponentialBackoff = true;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Creates a default retry configuration for this component.</summary>");
        sb.AppendLine(value: $"    public static {model.TypeName}RetryConfiguration CreateDefault() =>");
        sb.AppendLine(value: $"        new {model.TypeName}RetryConfiguration(MaxAttempts, TimeSpan.FromSeconds(BaseDelaySeconds), UseExponentialBackoff);");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated retry configuration record for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"public sealed record {model.TypeName}RetryConfiguration(");
        sb.AppendLine(value: "    int MaxAttempts,");
        sb.AppendLine(value: "    TimeSpan BaseDelay,");
        sb.AppendLine(value: "    bool UseExponentialBackoff);");

        ctx.AddSource(hintName: $"{model.TypeName}RetrySettings.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record RetryPolicyModel(string TypeName, string Namespace);
}
