using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class RetryPolicyGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Resilience.VcRetryPolicyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static RetryPolicyModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
        return new RetryPolicyModel(typeSymbol.Name, ns);
    }

    private static void Execute(SourceProductionContext ctx, RetryPolicyModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Auto-generated retry policy settings for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public static class {model.TypeName}RetrySettings");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Maximum number of retry attempts before failing.</summary>");
        sb.AppendLine("    public const int MaxAttempts = 3;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Base delay between retry attempts in seconds.</summary>");
        sb.AppendLine("    public const double BaseDelaySeconds = 1.0;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Maximum delay cap between retry attempts in seconds.</summary>");
        sb.AppendLine("    public const double MaxDelaySeconds = 30.0;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Whether to use exponential backoff between retries.</summary>");
        sb.AppendLine("    public const bool UseExponentialBackoff = true;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a default retry configuration for this component.</summary>");
        sb.AppendLine($"    public static {model.TypeName}RetryConfiguration CreateDefault() =>");
        sb.AppendLine($"        new {model.TypeName}RetryConfiguration(MaxAttempts, TimeSpan.FromSeconds(BaseDelaySeconds), UseExponentialBackoff);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated retry configuration record for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public sealed record {model.TypeName}RetryConfiguration(");
        sb.AppendLine("    int MaxAttempts,");
        sb.AppendLine("    TimeSpan BaseDelay,");
        sb.AppendLine("    bool UseExponentialBackoff);");

        ctx.AddSource($"{model.TypeName}RetrySettings.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record RetryPolicyModel(string TypeName, string Namespace);
}
