using System.Text;

namespace VisionaryCoder.Generators.Resilience;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class TimeoutPolicyGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Resilience.VcTimeoutPolicyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static TimeoutPolicyModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
        return new TimeoutPolicyModel(TypeName: typeSymbol.Name, Namespace: ns);
    }

    private static void Execute(SourceProductionContext ctx, TimeoutPolicyModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(value: model.Namespace))
        {
            sb.AppendLine(value: $"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine(value: $"/// <summary>Auto-generated timeout policy settings for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"public static class {model.TypeName}TimeoutSettings");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Default operation timeout in seconds.</summary>");
        sb.AppendLine(value: "    public const double DefaultTimeoutSeconds = 30.0;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Timeout for long-running operations in seconds.</summary>");
        sb.AppendLine(value: "    public const double LongRunningTimeoutSeconds = 120.0;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Returns a <see cref=\"TimeSpan\"/> for the default timeout.</summary>");
        sb.AppendLine(value: "    public static TimeSpan Default => TimeSpan.FromSeconds(DefaultTimeoutSeconds);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Returns a <see cref=\"TimeSpan\"/> for the long-running timeout.</summary>");
        sb.AppendLine(value: "    public static TimeSpan LongRunning => TimeSpan.FromSeconds(LongRunningTimeoutSeconds);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Creates a default timeout configuration for this component.</summary>");
        sb.AppendLine(value: $"    public static {model.TypeName}TimeoutConfiguration CreateDefault() =>");
        sb.AppendLine(value: $"        new {model.TypeName}TimeoutConfiguration(Default, LongRunning);");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated timeout configuration record for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"public sealed record {model.TypeName}TimeoutConfiguration(");
        sb.AppendLine(value: "    TimeSpan DefaultTimeout,");
        sb.AppendLine(value: "    TimeSpan LongRunningTimeout);");

        ctx.AddSource(hintName: $"{model.TypeName}TimeoutSettings.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record TimeoutPolicyModel(string TypeName, string Namespace);
}
