using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class TimeoutPolicyGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Resilience.VcTimeoutPolicyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static TimeoutPolicyModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
        return new TimeoutPolicyModel(typeSymbol.Name, ns);
    }

    private static void Execute(SourceProductionContext ctx, TimeoutPolicyModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Auto-generated timeout policy settings for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public static class {model.TypeName}TimeoutSettings");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Default operation timeout in seconds.</summary>");
        sb.AppendLine("    public const double DefaultTimeoutSeconds = 30.0;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Timeout for long-running operations in seconds.</summary>");
        sb.AppendLine("    public const double LongRunningTimeoutSeconds = 120.0;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns a <see cref=\"TimeSpan\"/> for the default timeout.</summary>");
        sb.AppendLine("    public static TimeSpan Default => TimeSpan.FromSeconds(DefaultTimeoutSeconds);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Returns a <see cref=\"TimeSpan\"/> for the long-running timeout.</summary>");
        sb.AppendLine("    public static TimeSpan LongRunning => TimeSpan.FromSeconds(LongRunningTimeoutSeconds);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a default timeout configuration for this component.</summary>");
        sb.AppendLine($"    public static {model.TypeName}TimeoutConfiguration CreateDefault() =>");
        sb.AppendLine($"        new {model.TypeName}TimeoutConfiguration(Default, LongRunning);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated timeout configuration record for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public sealed record {model.TypeName}TimeoutConfiguration(");
        sb.AppendLine("    TimeSpan DefaultTimeout,");
        sb.AppendLine("    TimeSpan LongRunningTimeout);");

        ctx.AddSource($"{model.TypeName}TimeoutSettings.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record TimeoutPolicyModel(string TypeName, string Namespace);
}
