using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates aggregate root base classes with identity and domain events.
/// Targets classes decorated with [VcAggregateRootAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AggregateRootGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcAggregateRootAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static AggregateRootModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new AggregateRootModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, AggregateRootModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Base class for domain aggregate roots.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public abstract partial class AggregateRoot");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly List<object> _domainEvents = new();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the aggregate root ID.</summary>");
        sb.AppendLine("    public Guid Id { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the version for concurrency control.</summary>");
        sb.AppendLine("    public int Version { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the domain events raised by this aggregate.</summary>");
        sb.AppendLine("    public IReadOnlyList<object> DomainEvents => _domainEvents.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds a domain event to the aggregate's event collection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected void RaiseDomainEvent(object domainEvent)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (domainEvent == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(domainEvent), \"Domain event cannot be null.\");");
        sb.AppendLine("        _domainEvents.Add(domainEvent);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Clears all domain events from the aggregate.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void ClearDomainEvents() => _domainEvents.Clear();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Increments the version for optimistic concurrency control.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected void IncrementVersion() => Version++;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Aggregate root for {model.AggregateRootName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.AggregateRootName} : AggregateRoot");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Initializes a new {model.AggregateRootName}.</summary>");
        sb.AppendLine($"    public {model.AggregateRootName}(Guid id)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (id == Guid.Empty)");
        sb.AppendLine("            throw new ArgumentException(\"Aggregate ID cannot be empty.\", nameof(id));");
        sb.AppendLine("        Id = id;");
        sb.AppendLine("        Version = 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Determines whether two aggregates are equal based on identity.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override bool Equals(object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return obj is {model.AggregateRootName} other && Id == other.Id;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Serves as the default hash function.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override int GetHashCode() => Id.GetHashCode();");
        sb.AppendLine("}");

        ctx.AddSource($"{model.AggregateRootName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record AggregateRootModel(string AggregateRootName, string Namespace);
}
