using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates aggregate root base classes with identity and domain events.
/// Targets classes decorated with [VcAggregateRootAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class AggregateRootGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcAggregateRootAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static AggregateRootModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new AggregateRootModel(
            AggregateRootName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, AggregateRootModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Base class for domain aggregate roots.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public abstract partial class AggregateRoot");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    private readonly List<object> _domainEvents = new();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the aggregate root ID.</summary>");
        sb.AppendLine(value: "    public Guid Id { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the version for concurrency control.</summary>");
        sb.AppendLine(value: "    public int Version { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the domain events raised by this aggregate.</summary>");
        sb.AppendLine(value: "    public IReadOnlyList<object> DomainEvents => _domainEvents.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Adds a domain event to the aggregate's event collection.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected void RaiseDomainEvent(object domainEvent)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (domainEvent == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(domainEvent), \"Domain event cannot be null.\");");
        sb.AppendLine(value: "        _domainEvents.Add(domainEvent);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Clears all domain events from the aggregate.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public void ClearDomainEvents() => _domainEvents.Clear();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Increments the version for optimistic concurrency control.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected void IncrementVersion() => Version++;");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Aggregate root for {model.AggregateRootName}.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.AggregateRootName} : AggregateRoot");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    /// <summary>Initializes a new {model.AggregateRootName}.</summary>");
        sb.AppendLine(value: $"    public {model.AggregateRootName}(Guid id)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (id == Guid.Empty)");
        sb.AppendLine(value: "            throw new ArgumentException(\"Aggregate ID cannot be empty.\", nameof(id));");
        sb.AppendLine(value: "        Id = id;");
        sb.AppendLine(value: "        Version = 0;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Determines whether two aggregates are equal based on identity.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override bool Equals(object? obj)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: $"        return obj is {model.AggregateRootName} other && Id == other.Id;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Serves as the default hash function.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override int GetHashCode() => Id.GetHashCode();");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.AggregateRootName}.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record AggregateRootModel(string AggregateRootName, string Namespace);
}
