using Microsoft.CodeAnalysis;

namespace Vc.Generators.Domain;

[Generator(LanguageNames.CSharp)]
public sealed class DomainModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // TODO: Set up syntax provider, transform to metadata, and emit generated code.
    }
}


[Generator(LanguageNames.CSharp)]
public sealed class StrongIdGenerator() : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("StrongId.g.cs", """
                // <auto-generated />
                namespace Vc.Generated.Domain;

                public readonly partial struct StrongId<T>(Guid Value);
                """);
        });
    }
}
