using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates CQRS command handler classes.
/// Targets classes decorated with [VcCommandHandlerAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class CommandHandlerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcCommandHandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static CommandHandlerModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new CommandHandlerModel(
            CommandName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, CommandHandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Base interface for CQRS command handlers.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public interface ICommandHandler<in TCommand>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Handles the command asynchronously.</summary>");
        sb.AppendLine(value: "    Task HandleAsync(TCommand command, CancellationToken cancellationToken = default);");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Base interface for CQRS command handlers with return values.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public interface ICommandHandler<in TCommand, TResult>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Handles the command asynchronously and returns a result.</summary>");
        sb.AppendLine(value: "    Task<TResult> HandleAsync(TCommand command, CancellationToken cancellationToken = default);");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Command handler for {model.CommandName}.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public abstract partial class {model.CommandName}Handler : ICommandHandler<{model.CommandName}>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Executes the command handler logic.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    protected abstract Task ExecuteAsync({model.CommandName} command, CancellationToken cancellationToken);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Handles the command asynchronously.</summary>");
        sb.AppendLine(value: $"    public async Task HandleAsync({model.CommandName} command, CancellationToken cancellationToken = default)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (command == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(command), \"Command cannot be null.\");");
        sb.AppendLine(value: "        await ExecuteAsync(command, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.CommandName}Handler.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record CommandHandlerModel(string CommandName, string Namespace);
}
