using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class CommandHandlerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.CommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static CommandHandlerModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new CommandHandlerModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, CommandHandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public interface ICommandHandler<in TCommand> where TCommand : notnull");
        sb.AppendLine("{");
        sb.AppendLine("    Task HandleAsync(TCommand command, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {model.CommandName}Handler : ICommandHandler<{model.CommandName}>");
        sb.AppendLine("{");
        sb.AppendLine("    public Task HandleAsync(" + $"{model.CommandName} command, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Implement command handling");
        sb.AppendLine("        throw new NotImplementedException();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Pipeline hooks (optional partial methods)");
        sb.AppendLine("    partial void OnBeforeHandle(" + $"{model.CommandName} command);");
        sb.AppendLine("    partial void OnAfterHandle(" + $"{model.CommandName} command);");
        sb.AppendLine("}");

        ctx.AddSource($"{model.CommandName}Handler.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record CommandHandlerModel(string CommandName, string Namespace);
}
