using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates CQRS command handler classes.
/// Targets classes decorated with [VcCommandHandlerAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CommandHandlerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcCommandHandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static CommandHandlerModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new CommandHandlerModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, CommandHandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Base interface for CQRS command handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public interface ICommandHandler<in TCommand>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Handles the command asynchronously.</summary>");
        sb.AppendLine("    Task HandleAsync(TCommand command, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Base interface for CQRS command handlers with return values.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public interface ICommandHandler<in TCommand, TResult>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Handles the command asynchronously and returns a result.</summary>");
        sb.AppendLine("    Task<TResult> HandleAsync(TCommand command, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Command handler for {model.CommandName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public abstract partial class {model.CommandName}Handler : ICommandHandler<{model.CommandName}>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Executes the command handler logic.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    protected abstract Task ExecuteAsync({model.CommandName} command, CancellationToken cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Handles the command asynchronously.</summary>");
        sb.AppendLine($"    public async Task HandleAsync({model.CommandName} command, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (command == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(command), \"Command cannot be null.\");");
        sb.AppendLine("        await ExecuteAsync(command, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.CommandName}Handler.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record CommandHandlerModel(string CommandName, string Namespace);
}
