using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates domain event interfaces and base classes for event classes.
/// Targets classes decorated with [VcDomainEventAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class DomainEventGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcDomainEventAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static DomainEventModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new DomainEventModel(
            EventName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, DomainEventModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Base class for all domain events.");
        sb.AppendLine(value: "/// </summary>");;
        sb.AppendLine(value: "public abstract class DomainEventBase");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Gets the event ID.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public Guid EventId { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the timestamp when the event occurred.</summary>");
        sb.AppendLine(value: "    public DateTime OccurredAt { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the aggregate root ID associated with this event.</summary>");
        sb.AppendLine(value: "    public Guid AggregateId { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the version of the aggregate when this event occurred.</summary>");
        sb.AppendLine(value: "    public int AggregateVersion { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Initializes a new instance of the DomainEventBase class.</summary>");
        sb.AppendLine(value: "    protected DomainEventBase(Guid aggregateId, int aggregateVersion)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        EventId = Guid.NewGuid();");
        sb.AppendLine(value: "        OccurredAt = DateTime.UtcNow;");
        sb.AppendLine(value: "        AggregateId = aggregateId;");
        sb.AppendLine(value: "        AggregateVersion = aggregateVersion;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Interface for {model.EventName} domain event.");
        sb.AppendLine(value: "/// </summary>");;
        sb.AppendLine(value: $"public interface I{model.EventName}Event");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Gets the event ID.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    Guid EventId { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the timestamp when the event occurred.</summary>");
        sb.AppendLine(value: "    DateTime OccurredAt { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the aggregate root ID associated with this event.</summary>");
        sb.AppendLine(value: "    Guid AggregateId { get; }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Domain event for {model.EventName}.");
        sb.AppendLine(value: "/// </summary>");;
        sb.AppendLine(value: $"public sealed partial class {model.EventName}Event : DomainEventBase, I{model.EventName}Event");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    /// <summary>Initializes a new instance of the {model.EventName}Event class.</summary>");
        sb.AppendLine(value: $"    public {model.EventName}Event(Guid aggregateId, int aggregateVersion)");
        sb.AppendLine(value: "        : base(aggregateId, aggregateVersion)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.EventName}Event.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record DomainEventModel(string EventName, string Namespace);
}



