using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates domain event interfaces and base classes for event classes.
/// Targets classes decorated with [VcDomainEventAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DomainEventGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcDomainEventAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static DomainEventModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new DomainEventModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, DomainEventModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Base class for all domain events.");
        sb.AppendLine("/// </summary>");;
        sb.AppendLine("public abstract class DomainEventBase");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the event ID.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public Guid EventId { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the timestamp when the event occurred.</summary>");
        sb.AppendLine("    public DateTime OccurredAt { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the aggregate root ID associated with this event.</summary>");
        sb.AppendLine("    public Guid AggregateId { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the version of the aggregate when this event occurred.</summary>");
        sb.AppendLine("    public int AggregateVersion { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Initializes a new instance of the DomainEventBase class.</summary>");
        sb.AppendLine("    protected DomainEventBase(Guid aggregateId, int aggregateVersion)");
        sb.AppendLine("    {");
        sb.AppendLine("        EventId = Guid.NewGuid();");
        sb.AppendLine("        OccurredAt = DateTime.UtcNow;");
        sb.AppendLine("        AggregateId = aggregateId;");
        sb.AppendLine("        AggregateVersion = aggregateVersion;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Interface for {model.EventName} domain event.");
        sb.AppendLine("/// </summary>");;
        sb.AppendLine($"public interface I{model.EventName}Event");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the event ID.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    Guid EventId { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the timestamp when the event occurred.</summary>");
        sb.AppendLine("    DateTime OccurredAt { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the aggregate root ID associated with this event.</summary>");
        sb.AppendLine("    Guid AggregateId { get; }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Domain event for {model.EventName}.");
        sb.AppendLine("/// </summary>");;
        sb.AppendLine($"public sealed partial class {model.EventName}Event : DomainEventBase, I{model.EventName}Event");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Initializes a new instance of the {model.EventName}Event class.</summary>");
        sb.AppendLine($"    public {model.EventName}Event(Guid aggregateId, int aggregateVersion)");
        sb.AppendLine("        : base(aggregateId, aggregateVersion)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EventName}Event.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record DomainEventModel(string EventName, string Namespace);
}



