using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates event-sourced aggregate classes for event replay and reconstruction.
/// Targets classes decorated with [VcEventSourcingAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EventSourcingGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcEventSourcingAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static EventSourcingModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new EventSourcingModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, EventSourcingModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Base class for event-sourced aggregates.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public abstract partial class EventSourcedAggregate");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly List<object> _uncommittedEvents = new();");
        sb.AppendLine("    private readonly List<object> _committedEvents = new();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the aggregate root ID.</summary>");
        sb.AppendLine("    public Guid AggregateId { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the aggregate version (event count).</summary>");
        sb.AppendLine("    public int Version { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets uncommitted domain events.</summary>");
        sb.AppendLine("    public IReadOnlyList<object> UncommittedEvents => _uncommittedEvents.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets all committed events.</summary>");
        sb.AppendLine("    public IReadOnlyList<object> CommittedEvents => _committedEvents.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies an event to the aggregate state.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected abstract void ApplyEvent(object @event);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Raises an event and applies it to aggregate state.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected void RaiseEvent(object @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (@event == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine("        ApplyEvent(@event);");
        sb.AppendLine("        _uncommittedEvents.Add(@event);");
        sb.AppendLine("        Version++;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Loads aggregate from event history.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void LoadFromHistory(IEnumerable<object> events)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (events == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(events), \"Events cannot be null.\");");
        sb.AppendLine("        foreach (var @event in events)");
        sb.AppendLine("            ApplyEvent(@event);");
        sb.AppendLine("        _committedEvents.AddRange(events);");
        sb.AppendLine("        Version = _committedEvents.Count;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Marks all uncommitted events as committed.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void MarkEventsAsCommitted()");
        sb.AppendLine("    {");
        sb.AppendLine("        _committedEvents.AddRange(_uncommittedEvents);");
        sb.AppendLine("        _uncommittedEvents.Clear();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Event-sourced aggregate for {model.AggregateRootName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.AggregateRootName}EventSourced : EventSourcedAggregate");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Initializes a new {model.AggregateRootName}EventSourced.</summary>");
        sb.AppendLine($"    public {model.AggregateRootName}EventSourced(Guid aggregateId)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (aggregateId == Guid.Empty)");
        sb.AppendLine("            throw new ArgumentException(\"Aggregate ID cannot be empty.\", nameof(aggregateId));");
        sb.AppendLine("        AggregateId = aggregateId;");
        sb.AppendLine("        Version = 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies an event to the aggregate state.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected override void ApplyEvent(object @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (@event == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine("        // Event handler dispatch would be implemented by derived classes");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.AggregateRootName}EventSourced.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record EventSourcingModel(string AggregateRootName, string Namespace);
}
