using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates event publisher classes for domain event publishing.
/// Targets interfaces decorated with [VcEventPublisherAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EventPublisherGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcEventPublisherAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static EventPublisherModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new EventPublisherModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, EventPublisherModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Event publisher implementation for publishing domain events.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {GetImplementationName(model.PublisherName)} : {model.PublisherName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly List<object> _events = new();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the collection of unpublished events.</summary>");
        sb.AppendLine("    public IReadOnlyList<object> Events => _events.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Publishes a domain event.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"@event\">The event to publish.</param>");
        sb.AppendLine("    public void Publish(object @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (@event == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine("        _events.Add(@event);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Publishes a domain event asynchronously.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"@event\">The event to publish.</param>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("    /// <returns>Task representing the asynchronous publication.</returns>");
        sb.AppendLine("    public Task PublishAsync(object @event, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        Publish(@event);");
        sb.AppendLine("        return Task.CompletedTask;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Clears all unpublished events.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void ClearEvents() => _events.Clear();");
        sb.AppendLine("}");

        ctx.AddSource($"{GetImplementationName(model.PublisherName)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetImplementationName(string publisherName)
    {
        // If the interface starts with 'I', remove it; otherwise append 'Impl'
        return publisherName.StartsWith("I") ? publisherName.Substring(1) : $"{publisherName}Impl";
    }

    private sealed record EventPublisherModel(string PublisherName, string Namespace);
}
