using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates event projection classes for read models.
/// Targets classes decorated with [VcEventProjectionAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class EventProjectionGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcEventProjectionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static EventProjectionModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new EventProjectionModel(
            ProjectionName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, EventProjectionModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Base class for event projections (read models).");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public abstract partial class EventProjection");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Gets the projection ID.</summary>");
        sb.AppendLine(value: "    public Guid Id { get; protected set; } = Guid.NewGuid();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the last event version applied.</summary>");
        sb.AppendLine(value: "    public long Version { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the last update timestamp.</summary>");
        sb.AppendLine(value: "    public DateTime LastUpdated { get; protected set; } = DateTime.UtcNow;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Handles an event and updates the projection state.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected abstract void ApplyEvent(object @event);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Processes an event for this projection.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public void Handle(object @event, long version)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (@event == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine(value: "        ApplyEvent(@event);");
        sb.AppendLine(value: "        Version = version;");
        sb.AppendLine(value: "        LastUpdated = DateTime.UtcNow;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Event projection (read model) for {model.ProjectionName}.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.ProjectionName}Projection : EventProjection");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    /// <summary>Gets the aggregate root ID associated with this projection.</summary>");
        sb.AppendLine(value: $"    public Guid AggregateId {{ get; set; }}");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Handles an event and updates the projection state.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected override void ApplyEvent(object @event)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (@event == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine(value: "        // Event handler dispatch implemented by derived classes");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.ProjectionName}Projection.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record EventProjectionModel(string ProjectionName, string Namespace);
}
