using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates event projection classes for read models.
/// Targets classes decorated with [VcEventProjectionAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EventProjectionGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcEventProjectionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static EventProjectionModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new EventProjectionModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, EventProjectionModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Base class for event projections (read models).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public abstract partial class EventProjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets the projection ID.</summary>");
        sb.AppendLine("    public Guid Id { get; protected set; } = Guid.NewGuid();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the last event version applied.</summary>");
        sb.AppendLine("    public long Version { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the last update timestamp.</summary>");
        sb.AppendLine("    public DateTime LastUpdated { get; protected set; } = DateTime.UtcNow;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Handles an event and updates the projection state.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected abstract void ApplyEvent(object @event);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Processes an event for this projection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void Handle(object @event, long version)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (@event == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine("        ApplyEvent(@event);");
        sb.AppendLine("        Version = version;");
        sb.AppendLine("        LastUpdated = DateTime.UtcNow;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Event projection (read model) for {model.ProjectionName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.ProjectionName}Projection : EventProjection");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Gets the aggregate root ID associated with this projection.</summary>");
        sb.AppendLine($"    public Guid AggregateId {{ get; set; }}");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Handles an event and updates the projection state.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected override void ApplyEvent(object @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (@event == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine("        // Event handler dispatch implemented by derived classes");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.ProjectionName}Projection.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record EventProjectionModel(string ProjectionName, string Namespace);
}
