using System.Text;

namespace VisionaryCoder.Generators.Domain;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class EventGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.DomainEventAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static EventModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new EventModel(EventName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, EventModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated event envelope for <see cref=\"{{model.EventName}}\"/> domain events.</summary>");
        sb.AppendLine(value: $"public sealed record {model.EventName}Envelope<TEvent>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    public required TEvent Event { get; init; }");
        sb.AppendLine(value: "    public required Guid CorrelationId { get; init; }");
        sb.AppendLine(value: "    public required Guid CausationId { get; init; }");
        sb.AppendLine(value: "    public required DateTimeOffset Timestamp { get; init; }");
        sb.AppendLine();
        sb.AppendLine(value: $"    public static {model.EventName}Envelope<TEvent> Create(TEvent @event, Guid correlationId = default, Guid causationId = default)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return new " + $"{model.EventName}Envelope<TEvent>");
        sb.AppendLine(value: "        {");
        sb.AppendLine(value: "            Event = @event,");
        sb.AppendLine(value: "            CorrelationId = correlationId == default ? Guid.NewGuid() : correlationId,");
        sb.AppendLine(value: "            CausationId = causationId == default ? Guid.NewGuid() : causationId,");
        sb.AppendLine(value: "            Timestamp = DateTimeOffset.UtcNow");
        sb.AppendLine(value: "        };");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.EventName}Envelope.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record EventModel(string EventName, string Namespace);
}
