using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates event publisher classes for domain event publishing.
/// Targets interfaces decorated with [VcEventPublisherAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class EventPublisherGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcEventPublisherAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static EventPublisherModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new EventPublisherModel(
            PublisherName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, EventPublisherModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Event publisher implementation for publishing domain events.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {GetImplementationName(publisherName: model.PublisherName)} : {model.PublisherName}");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    private readonly List<object> _events = new();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the collection of unpublished events.</summary>");
        sb.AppendLine(value: "    public IReadOnlyList<object> Events => _events.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Publishes a domain event.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"@event\">The event to publish.</param>");
        sb.AppendLine(value: "    public void Publish(object @event)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (@event == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine(value: "        _events.Add(@event);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Publishes a domain event asynchronously.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"@event\">The event to publish.</param>");
        sb.AppendLine(value: "    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine(value: "    /// <returns>Task representing the asynchronous publication.</returns>");
        sb.AppendLine(value: "    public Task PublishAsync(object @event, CancellationToken cancellationToken = default)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        Publish(@event);");
        sb.AppendLine(value: "        return Task.CompletedTask;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Clears all unpublished events.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public void ClearEvents() => _events.Clear();");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{GetImplementationName(publisherName: model.PublisherName)}.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private static string GetImplementationName(string publisherName)
    {
        // If the interface starts with 'I', remove it; otherwise append 'Impl'
        return publisherName.StartsWith(value: "I") ? publisherName.Substring(startIndex: 1) : $"{publisherName}Impl";
    }

    private sealed record EventPublisherModel(string PublisherName, string Namespace);
}
