using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class EventGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.DomainEventAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static EventModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new EventModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, EventModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated event envelope for <see cref=\"{{model.EventName}}\"/> domain events.</summary>");
        sb.AppendLine($"public sealed record {model.EventName}Envelope<TEvent>");
        sb.AppendLine("{");
        sb.AppendLine("    public required TEvent Event { get; init; }");
        sb.AppendLine("    public required Guid CorrelationId { get; init; }");
        sb.AppendLine("    public required Guid CausationId { get; init; }");
        sb.AppendLine("    public required DateTimeOffset Timestamp { get; init; }");
        sb.AppendLine();
        sb.AppendLine($"    public static {model.EventName}Envelope<TEvent> Create(TEvent @event, Guid correlationId = default, Guid causationId = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return new " + $"{model.EventName}Envelope<TEvent>");
        sb.AppendLine("        {");
        sb.AppendLine("            Event = @event,");
        sb.AppendLine("            CorrelationId = correlationId == default ? Guid.NewGuid() : correlationId,");
        sb.AppendLine("            CausationId = causationId == default ? Guid.NewGuid() : causationId,");
        sb.AppendLine("            Timestamp = DateTimeOffset.UtcNow");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EventName}Envelope.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record EventModel(string EventName, string Namespace);
}
