using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates event-sourced aggregate classes for event replay and reconstruction.
/// Targets classes decorated with [VcEventSourcingAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class EventSourcingGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcEventSourcingAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static EventSourcingModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new EventSourcingModel(
            AggregateRootName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, EventSourcingModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Base class for event-sourced aggregates.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public abstract partial class EventSourcedAggregate");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    private readonly List<object> _uncommittedEvents = new();");
        sb.AppendLine(value: "    private readonly List<object> _committedEvents = new();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the aggregate root ID.</summary>");
        sb.AppendLine(value: "    public Guid AggregateId { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the aggregate version (event count).</summary>");
        sb.AppendLine(value: "    public int Version { get; protected set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets uncommitted domain events.</summary>");
        sb.AppendLine(value: "    public IReadOnlyList<object> UncommittedEvents => _uncommittedEvents.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets all committed events.</summary>");
        sb.AppendLine(value: "    public IReadOnlyList<object> CommittedEvents => _committedEvents.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Applies an event to the aggregate state.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected abstract void ApplyEvent(object @event);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Raises an event and applies it to aggregate state.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected void RaiseEvent(object @event)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (@event == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine(value: "        ApplyEvent(@event);");
        sb.AppendLine(value: "        _uncommittedEvents.Add(@event);");
        sb.AppendLine(value: "        Version++;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Loads aggregate from event history.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public void LoadFromHistory(IEnumerable<object> events)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (events == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(events), \"Events cannot be null.\");");
        sb.AppendLine(value: "        foreach (var @event in events)");
        sb.AppendLine(value: "            ApplyEvent(@event);");
        sb.AppendLine(value: "        _committedEvents.AddRange(events);");
        sb.AppendLine(value: "        Version = _committedEvents.Count;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Marks all uncommitted events as committed.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public void MarkEventsAsCommitted()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        _committedEvents.AddRange(_uncommittedEvents);");
        sb.AppendLine(value: "        _uncommittedEvents.Clear();");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Event-sourced aggregate for {model.AggregateRootName}.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.AggregateRootName}EventSourced : EventSourcedAggregate");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    /// <summary>Initializes a new {model.AggregateRootName}EventSourced.</summary>");
        sb.AppendLine(value: $"    public {model.AggregateRootName}EventSourced(Guid aggregateId)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (aggregateId == Guid.Empty)");
        sb.AppendLine(value: "            throw new ArgumentException(\"Aggregate ID cannot be empty.\", nameof(aggregateId));");
        sb.AppendLine(value: "        AggregateId = aggregateId;");
        sb.AppendLine(value: "        Version = 0;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Applies an event to the aggregate state.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected override void ApplyEvent(object @event)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (@event == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(@event), \"Event cannot be null.\");");
        sb.AppendLine(value: "        // Event handler dispatch would be implemented by derived classes");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.AggregateRootName}EventSourced.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record EventSourcingModel(string AggregateRootName, string Namespace);
}
