using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class QueryHandlerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.QueryAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static QueryHandlerModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new QueryHandlerModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, QueryHandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public interface IQueryHandler<in TQuery, TResult> where TQuery : notnull");
        sb.AppendLine("{");
        sb.AppendLine("    Task<TResult> HandleAsync(TQuery query, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {model.QueryName}Handler : IQueryHandler<{model.QueryName}, object>");
        sb.AppendLine("{");
        sb.AppendLine("    public Task<object> HandleAsync(" + $"{model.QueryName} query, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Implement query handling");
        sb.AppendLine("        throw new NotImplementedException();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Caching hook (optional partial method)");
        sb.AppendLine("    partial void OnBeforeHandle(" + $"{model.QueryName} query);");
        sb.AppendLine("}");

        ctx.AddSource($"{model.QueryName}Handler.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record QueryHandlerModel(string QueryName, string Namespace);
}
