using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates CQRS query handler classes.
/// Targets classes decorated with [VcQueryHandlerAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class QueryHandlerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcQueryHandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static QueryHandlerModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new QueryHandlerModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, QueryHandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Base interface for CQRS query handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public interface IQueryHandler<in TQuery, TResult>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Handles the query asynchronously and returns a result.</summary>");
        sb.AppendLine("    Task<TResult> HandleAsync(TQuery query, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Query handler for {model.QueryName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public abstract partial class {model.QueryName}Handler : IQueryHandler<{model.QueryName}, object?>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Executes the query handler logic and returns results.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    protected abstract Task<object?> ExecuteAsync({model.QueryName} query, CancellationToken cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Handles the query asynchronously and returns results.</summary>");
        sb.AppendLine($"    public async Task<object?> HandleAsync({model.QueryName} query, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (query == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(query), \"Query cannot be null.\");");
        sb.AppendLine("        return await ExecuteAsync(query, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.QueryName}Handler.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record QueryHandlerModel(string QueryName, string Namespace);
}
