using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates CQRS query handler classes.
/// Targets classes decorated with [VcQueryHandlerAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class QueryHandlerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcQueryHandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static QueryHandlerModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new QueryHandlerModel(
            QueryName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, QueryHandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Base interface for CQRS query handlers.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public interface IQueryHandler<in TQuery, TResult>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Handles the query asynchronously and returns a result.</summary>");
        sb.AppendLine(value: "    Task<TResult> HandleAsync(TQuery query, CancellationToken cancellationToken = default);");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Query handler for {model.QueryName}.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public abstract partial class {model.QueryName}Handler : IQueryHandler<{model.QueryName}, object?>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Executes the query handler logic and returns results.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    protected abstract Task<object?> ExecuteAsync({model.QueryName} query, CancellationToken cancellationToken);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Handles the query asynchronously and returns results.</summary>");
        sb.AppendLine(value: $"    public async Task<object?> HandleAsync({model.QueryName} query, CancellationToken cancellationToken = default)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (query == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(query), \"Query cannot be null.\");");
        sb.AppendLine(value: "        return await ExecuteAsync(query, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.QueryName}Handler.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record QueryHandlerModel(string QueryName, string Namespace);
}
