using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates Result<TSuccess, TError> types for monadic error handling.
/// Targets classes decorated with [VcResultAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class ResultGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcResultAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static ResultModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new ResultModel(
            ResultName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, ResultModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Represents a result of an operation that can succeed or fail.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public abstract partial class Result");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Gets whether this result is successful.</summary>");
        sb.AppendLine(value: "    public abstract bool IsSuccess { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets whether this result is a failure.</summary>");
        sb.AppendLine(value: "    public bool IsFailure => !IsSuccess;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Applies a function to success and failure cases.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public abstract TResult Match<TResult>(");
        sb.AppendLine(value: "        Func<object?, TResult> onSuccess,");
        sb.AppendLine(value: "        Func<string, TResult> onFailure);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Binds a function that returns a Result.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public abstract Result Bind(Func<object?, Result> binder);");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Represents a successful result with a value.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public sealed partial class Success : Result");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Gets the success value.</summary>");
        sb.AppendLine(value: "    public object? Value { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets whether this result is successful.</summary>");
        sb.AppendLine(value: "    public override bool IsSuccess => true;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Initializes a new Success.</summary>");
        sb.AppendLine(value: "    public Success(object? value)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        Value = value;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Applies a function to success and failure cases.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override TResult Match<TResult>(");
        sb.AppendLine(value: "        Func<object?, TResult> onSuccess,");
        sb.AppendLine(value: "        Func<string, TResult> onFailure)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (onSuccess == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(onSuccess));");
        sb.AppendLine(value: "        return onSuccess(Value);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Binds a function that returns a Result.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override Result Bind(Func<object?, Result> binder)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (binder == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(binder));");
        sb.AppendLine(value: "        return binder(Value);");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Represents a failed result with an error message.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public sealed partial class Failure : Result");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Gets the error message.</summary>");
        sb.AppendLine(value: "    public string Error { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets whether this result is successful.</summary>");
        sb.AppendLine(value: "    public override bool IsSuccess => false;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Initializes a new Failure.</summary>");
        sb.AppendLine(value: "    public Failure(string error)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (string.IsNullOrWhiteSpace(error))");
        sb.AppendLine(value: "            throw new ArgumentException(\"Error message cannot be empty.\", nameof(error));");
        sb.AppendLine(value: "        Error = error;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Applies a function to success and failure cases.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override TResult Match<TResult>(");
        sb.AppendLine(value: "        Func<object?, TResult> onSuccess,");
        sb.AppendLine(value: "        Func<string, TResult> onFailure)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (onFailure == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(onFailure));");
        sb.AppendLine(value: "        return onFailure(Error);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Binds a function that returns a Result.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override Result Bind(Func<object?, Result> binder)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (binder == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(binder));");
        sb.AppendLine(value: "        return this;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Result type for {model.ResultName}.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.ResultName}Result");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    /// <summary>Creates a successful {model.ResultName}Result.</summary>");
        sb.AppendLine(value: $"    public static Result Success(object? value) => new Success(value);");
        sb.AppendLine();
        sb.AppendLine(value: $"    /// <summary>Creates a failed {model.ResultName}Result.</summary>");
        sb.AppendLine(value: $"    public static Result Failure(string error) => new Failure(error);");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.ResultName}Result.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record ResultModel(string ResultName, string Namespace);
}
