using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates Result<TSuccess, TError> types for monadic error handling.
/// Targets classes decorated with [VcResultAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ResultGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcResultAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static ResultModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new ResultModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, ResultModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Represents a result of an operation that can succeed or fail.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public abstract partial class Result");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets whether this result is successful.</summary>");
        sb.AppendLine("    public abstract bool IsSuccess { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets whether this result is a failure.</summary>");
        sb.AppendLine("    public bool IsFailure => !IsSuccess;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies a function to success and failure cases.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public abstract TResult Match<TResult>(");
        sb.AppendLine("        Func<object?, TResult> onSuccess,");
        sb.AppendLine("        Func<string, TResult> onFailure);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Binds a function that returns a Result.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public abstract Result Bind(Func<object?, Result> binder);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Represents a successful result with a value.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed partial class Success : Result");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets the success value.</summary>");
        sb.AppendLine("    public object? Value { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets whether this result is successful.</summary>");
        sb.AppendLine("    public override bool IsSuccess => true;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Initializes a new Success.</summary>");
        sb.AppendLine("    public Success(object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        Value = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies a function to success and failure cases.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override TResult Match<TResult>(");
        sb.AppendLine("        Func<object?, TResult> onSuccess,");
        sb.AppendLine("        Func<string, TResult> onFailure)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (onSuccess == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(onSuccess));");
        sb.AppendLine("        return onSuccess(Value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Binds a function that returns a Result.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override Result Bind(Func<object?, Result> binder)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (binder == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(binder));");
        sb.AppendLine("        return binder(Value);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Represents a failed result with an error message.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed partial class Failure : Result");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets the error message.</summary>");
        sb.AppendLine("    public string Error { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets whether this result is successful.</summary>");
        sb.AppendLine("    public override bool IsSuccess => false;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Initializes a new Failure.</summary>");
        sb.AppendLine("    public Failure(string error)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(error))");
        sb.AppendLine("            throw new ArgumentException(\"Error message cannot be empty.\", nameof(error));");
        sb.AppendLine("        Error = error;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies a function to success and failure cases.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override TResult Match<TResult>(");
        sb.AppendLine("        Func<object?, TResult> onSuccess,");
        sb.AppendLine("        Func<string, TResult> onFailure)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (onFailure == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(onFailure));");
        sb.AppendLine("        return onFailure(Error);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Binds a function that returns a Result.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override Result Bind(Func<object?, Result> binder)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (binder == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(binder));");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Result type for {model.ResultName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.ResultName}Result");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Creates a successful {model.ResultName}Result.</summary>");
        sb.AppendLine($"    public static Result Success(object? value) => new Success(value);");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Creates a failed {model.ResultName}Result.</summary>");
        sb.AppendLine($"    public static Result Failure(string error) => new Failure(error);");
        sb.AppendLine("}");

        ctx.AddSource($"{model.ResultName}Result.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record ResultModel(string ResultName, string Namespace);
}
