using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class StateMachineGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.StateMachineAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static StateMachineModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new StateMachineModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, StateMachineModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>State machine for {model.TypeName}</summary>");
        sb.AppendLine($"public partial class {model.TypeName}StateMachine");
        sb.AppendLine("{");
        sb.AppendLine("    public enum StateType");
        sb.AppendLine("    {");
        sb.AppendLine("        // Define states here");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private StateType _currentState;");
        sb.AppendLine();
        sb.AppendLine("    public StateType CurrentState => _currentState;");
        sb.AppendLine();
        sb.AppendLine("    public bool CanTransition(StateType targetState) => true;"); // Placeholder
        sb.AppendLine();
        sb.AppendLine("    public bool TryTransition(StateType targetState)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!CanTransition(targetState)) return false;");
        sb.AppendLine("        _currentState = targetState;");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}StateMachine.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record StateMachineModel(string TypeName, string Namespace);
}
