using System.Text;

namespace VisionaryCoder.Generators.Domain;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class StateMachineGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.StateMachineAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static StateMachineModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new StateMachineModel(TypeName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, StateMachineModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>State machine for {model.TypeName}</summary>");
        sb.AppendLine(value: $"public partial class {model.TypeName}StateMachine");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    public enum StateType");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        // Define states here");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    private StateType _currentState;");
        sb.AppendLine();
        sb.AppendLine(value: "    public StateType CurrentState => _currentState;");
        sb.AppendLine();
        sb.AppendLine(value: "    public bool CanTransition(StateType targetState) => true;"); // Placeholder
        sb.AppendLine();
        sb.AppendLine(value: "    public bool TryTransition(StateType targetState)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (!CanTransition(targetState)) return false;");
        sb.AppendLine(value: "        _currentState = targetState;");
        sb.AppendLine(value: "        return true;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.TypeName}StateMachine.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record StateMachineModel(string TypeName, string Namespace);
}
