using System.Text;

namespace VisionaryCoder.Generators.Domain;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class StrongIdGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcStrongIdAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static StrongIdModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new StrongIdModel(TypeName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, StrongIdModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated strongly-typed identifier for <see cref=\"{{model.TypeName}}\"/>.</summary>");
        sb.AppendLine(value: $"public partial readonly struct {model.TypeName} : IEquatable<{model.TypeName}>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    public Guid Value { get; }");
        sb.AppendLine();
        sb.AppendLine(value: $"    public {model.TypeName}(Guid value) => Value = value;");
        sb.AppendLine();
        sb.AppendLine(value: "    public static bool operator ==(in " + $"{model.TypeName} left, in {model.TypeName} right) => left.Value == right.Value;");
        sb.AppendLine();
        sb.AppendLine(value: "    public static bool operator !=(in " + $"{model.TypeName} left, in {model.TypeName} right) => left.Value != right.Value;");
        sb.AppendLine();
        sb.AppendLine(value: "    public override bool Equals(object? obj) => obj is " + $"{model.TypeName} id && Equals(id);");
        sb.AppendLine();
        sb.AppendLine(value: $"    public bool Equals({model.TypeName} other) => Value == other.Value;");
        sb.AppendLine();
        sb.AppendLine(value: "    public override int GetHashCode() => Value.GetHashCode();");
        sb.AppendLine();
        sb.AppendLine(value: "    public override string ToString() => Value.ToString();");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.TypeName}.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record StrongIdModel(string TypeName, string Namespace);
}
