using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class StrongIdGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcStrongIdAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static StrongIdModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new StrongIdModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, StrongIdModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial readonly struct {model.TypeName} : IEquatable<{model.TypeName}>");
        sb.AppendLine("{");
        sb.AppendLine("    public Guid Value { get; }");
        sb.AppendLine();
        sb.AppendLine($"    public {model.TypeName}(Guid value) => Value = value;");
        sb.AppendLine();
        sb.AppendLine("    public static bool operator ==(in " + $"{model.TypeName} left, in {model.TypeName} right) => left.Value == right.Value;");
        sb.AppendLine();
        sb.AppendLine("    public static bool operator !=(in " + $"{model.TypeName} left, in {model.TypeName} right) => left.Value != right.Value;");
        sb.AppendLine();
        sb.AppendLine("    public override bool Equals(object? obj) => obj is " + $"{model.TypeName} id && Equals(id);");
        sb.AppendLine();
        sb.AppendLine($"    public bool Equals({model.TypeName} other) => Value == other.Value;");
        sb.AppendLine();
        sb.AppendLine("    public override int GetHashCode() => Value.GetHashCode();");
        sb.AppendLine();
        sb.AppendLine("    public override string ToString() => Value.ToString();");
        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record StrongIdModel(string TypeName, string Namespace);
}
