using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates immutable value object classes with equality and hashing.
/// Targets classes decorated with [VcValueObjectAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ValueObjectGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcValueObjectAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static ValueObjectModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new ValueObjectModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, ValueObjectModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Base class for value objects with immutability and equality semantics.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public abstract partial class ValueObject : IEquatable<ValueObject>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the constituent values used for equality comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected abstract IEnumerable<object?> GetEqualityComponents();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Determines whether two value objects are equal.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override bool Equals(object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine("        return obj is ValueObject other && Equals(other);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Determines whether two value objects are equal.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public virtual bool Equals(ValueObject? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        return other is not null && GetEqualityComponents().SequenceEqual(other.GetEqualityComponents());");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Serves as the default hash function.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override int GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        return GetEqualityComponents()");
        sb.AppendLine("            .Aggregate(default(HashCode), (hc, value) => { hc.Add(value); return hc; })");
        sb.AppendLine("            .GetHashCode();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Determines whether two value objects are equal.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static bool operator ==(ValueObject? left, ValueObject? right)");
        sb.AppendLine("    {");
        sb.AppendLine("        return left?.Equals(right) ?? right is null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Determines whether two value objects are not equal.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static bool operator !=(ValueObject? left, ValueObject? right)");
        sb.AppendLine("    {");
        sb.AppendLine("        return !(left == right);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Immutable value object {model.ObjectName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.ObjectName} : ValueObject");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the value.</summary>");
        sb.AppendLine("    public string Value { get; }");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Initializes a new {model.ObjectName}.</summary>");
        sb.AppendLine($"    public {model.ObjectName}(string value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(value))");
        sb.AppendLine("            throw new ArgumentException(\"Value cannot be null or empty.\", nameof(value));");
        sb.AppendLine("        Value = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the constituent values used for equality comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected override IEnumerable<object?> GetEqualityComponents()");
        sb.AppendLine("    {");
        sb.AppendLine("        yield return Value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Converts to string representation.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public override string ToString() => Value;");
        sb.AppendLine("}");

        ctx.AddSource($"{model.ObjectName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record ValueObjectModel(string ObjectName, string Namespace);
}
