using System.Text;

namespace VisionaryCoder.Generators.Domain;

/// <summary>
/// Generates immutable value object classes with equality and hashing.
/// Targets classes decorated with [VcValueObjectAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class ValueObjectGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Domain.VcValueObjectAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static ValueObjectModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new ValueObjectModel(
            ObjectName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, ValueObjectModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Base class for value objects with immutability and equality semantics.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public abstract partial class ValueObject : IEquatable<ValueObject>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Gets the constituent values used for equality comparison.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected abstract IEnumerable<object?> GetEqualityComponents();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Determines whether two value objects are equal.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override bool Equals(object? obj)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return obj is ValueObject other && Equals(other);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Determines whether two value objects are equal.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public virtual bool Equals(ValueObject? other)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return other is not null && GetEqualityComponents().SequenceEqual(other.GetEqualityComponents());");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Serves as the default hash function.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override int GetHashCode()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return GetEqualityComponents()");
        sb.AppendLine(value: "            .Aggregate(default(HashCode), (hc, value) => { hc.Add(value); return hc; })");
        sb.AppendLine(value: "            .GetHashCode();");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Determines whether two value objects are equal.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public static bool operator ==(ValueObject? left, ValueObject? right)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return left?.Equals(right) ?? right is null;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Determines whether two value objects are not equal.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public static bool operator !=(ValueObject? left, ValueObject? right)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return !(left == right);");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Immutable value object {model.ObjectName}.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.ObjectName} : ValueObject");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Gets the value.</summary>");
        sb.AppendLine(value: "    public string Value { get; }");
        sb.AppendLine();
        sb.AppendLine(value: $"    /// <summary>Initializes a new {model.ObjectName}.</summary>");
        sb.AppendLine(value: $"    public {model.ObjectName}(string value)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (string.IsNullOrWhiteSpace(value))");
        sb.AppendLine(value: "            throw new ArgumentException(\"Value cannot be null or empty.\", nameof(value));");
        sb.AppendLine(value: "        Value = value;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Gets the constituent values used for equality comparison.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    protected override IEnumerable<object?> GetEqualityComponents()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        yield return Value;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Converts to string representation.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public override string ToString() => Value;");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.ObjectName}.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record ValueObjectModel(string ObjectName, string Namespace);
}
