using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace VisionaryCoder.Generators.Design.Extensibility;

    [Generator]
    public sealed class CachingGenerator : ISourceGenerator
    {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not Receiver receiver)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace VisionaryCoder.Caching.Generated {");

            foreach (var method in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(method.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(method) as IMethodSymbol;
                if (symbol is null) continue;

                var className = symbol.ContainingType.Name;
                var methodName = symbol.Name;
                var returnType = symbol.ReturnType.ToDisplayString();

                sb.AppendLine($$"""
                    public static class {{className}}_{{methodName}}_Cache
                    {
                        private static {{returnType}}? _cached;
                        private static bool _hasValue;

                        public static {{returnType}} Invoke({{className}} instance)
                        {
                            if (_hasValue) return _cached!;
                            _cached = instance.{{methodName}}();
                            _hasValue = true;
                            return _cached!;
                        }
                    }
                """);
            }

            sb.AppendLine("}");

            context.AddSource("GeneratedCaching.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<MethodDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is MethodDeclarationSyntax m &&
                    m.AttributeLists.Any(a => a.Attributes.Any(attr =>
                        attr.Name.ToString().Contains("GenerateCache"))))
                {
                    Candidates.Add(m);
                }
            }
        }
    }

    [Generator]
    public sealed class CachingGenerator : ISourceGenerator
    {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not Receiver receiver)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace VisionaryCoder.Caching.Generated {");

            foreach (var method in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(method.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(method) as IMethodSymbol;
                if (symbol is null) continue;

                var className = symbol.ContainingType.Name;
                var methodName = symbol.Name;
                var returnType = symbol.ReturnType.ToDisplayString();

                sb.AppendLine($$"""
                    public static class {{className}}_{{methodName}}_Cache
                    {
                        private static {{returnType}}? _cached;
                        private static bool _hasValue;

                        public static {{returnType}} Invoke({{className}} instance)
                        {
                            if (_hasValue) return _cached!;
                            _cached = instance.{{methodName}}();
                            _hasValue = true;
                            return _cached!;
                        }
                    }
                """);
            }

            sb.AppendLine("}");

            context.AddSource("GeneratedCaching.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<MethodDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is MethodDeclarationSyntax m &&
                    m.AttributeLists.Any(a => a.Attributes.Any(attr =>
                        attr.Name.ToString().Contains("GenerateCache"))))
                {
                    Candidates.Add(m);
                }
            }
        }
    }

    [Generator]
    public sealed class RetryResilienceGenerator : ISourceGenerator
    {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not Receiver receiver)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace VisionaryCoder.Resilience.Generated {");

            foreach (var method in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(method.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(method) as IMethodSymbol;
                if (symbol is null) continue;

                var className = symbol.ContainingType.Name;
                var methodName = symbol.Name;
                var returnType = symbol.ReturnType.ToDisplayString();

                var attr = symbol.GetAttributes()
                    .First(a => a.AttributeClass!.Name.Contains("GenerateRetry"));
                var attempts = (int)attr.ConstructorArguments[0].Value!;

                sb.AppendLine($$"""
                    public static class {{className}}_{{methodName}}_Retry
                    {
                        public static {{returnType}} Invoke({{className}} instance)
                        {
                            int attempts = {{attempts}};
                            while (true)
                            {
                                try { return instance.{{methodName}}(); }
                                catch when (--attempts > 0) { }
                            }
                        }
                    }
                """);
            }

            sb.AppendLine("}");

            context.AddSource("GeneratedRetryPolicies.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<MethodDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is MethodDeclarationSyntax m &&
                    m.AttributeLists.Any(a => a.Attributes.Any(attr =>
                        attr.Name.ToString().Contains("GenerateRetry"))))
                {
                    Candidates.Add(m);
                }
            }
        }
    }

    [Generator]
    public sealed class MetricsGenerator : ISourceGenerator
    {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not Receiver receiver)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace VisionaryCoder.Metrics.Generated {");

            foreach (var method in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(method.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(method) as IMethodSymbol;
                if (symbol is null) continue;

                var className = symbol.ContainingType.Name;
                var methodName = symbol.Name;

                var attr = symbol.GetAttributes()
                    .First(a => a.AttributeClass!.Name.Contains("GenerateMetric"));
                var metricName = attr.ConstructorArguments[0].Value!.ToString();

                sb.AppendLine($$"""
                    public static class {{className}}_{{methodName}}_Metrics
                    {
                        private static int _count;

                        public static void Increment() => _count++;
                        public static int Count => _count;
                        public static string Name => "{{metricName}}";
                    }
                """);
            }

            sb.AppendLine("}");

            context.AddSource("GeneratedMetrics.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<MethodDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is MethodDeclarationSyntax m &&
                    m.AttributeLists.Any(a => a.Attributes.Any(attr =>
                        attr.Name.ToString().Contains("GenerateMetric"))))
                {
                    Candidates.Add(m);
                }
            }
        }
    }

    [Generator]
    public sealed class AuditTrailGenerator : ISourceGenerator
    {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not Receiver receiver)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace VisionaryCoder.Auditing.Generated {");

            foreach (var method in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(method.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(method) as IMethodSymbol;
                if (symbol is null) continue;

                var className = symbol.ContainingType.Name;
                var methodName = symbol.Name;

                sb.AppendLine($$"""
                    public static class {{className}}_{{methodName}}_Audit
                    {
                        public static void LogStart()
                            => System.Console.WriteLine($"[AUDIT] Starting {{className}}.{{methodName}}");

                        public static void LogEnd()
                            => System.Console.WriteLine($"[AUDIT] Completed {{className}}.{{methodName}}");
                    }
                """);
            }

            sb.AppendLine("}");

            context.AddSource("GeneratedAuditTrail.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<MethodDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is MethodDeclarationSyntax m &&
                    m.AttributeLists.Any(a => a.Attributes.Any(attr =>
                        attr.Name.ToString().Contains("GenerateAudit"))))
                {
                    Candidates.Add(m);
                }
            }
        }
    }

    [Generator]
    public sealed class SerializationGenerator : ISourceGenerator
    {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not Receiver receiver)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("namespace VisionaryCoder.Serialization.Generated {");

            foreach (var cls in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(cls.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(cls) as INamedTypeSymbol;
                if (symbol is null) continue;

                var className = symbol.Name;

                sb.AppendLine($$"""
                    public static class {{className}}_Serializer
                    {
                        public static string ToJson({{className}} value)
                            => JsonSerializer.Serialize(value);

                        public static {{className}} FromJson(string json)
                            => JsonSerializer.Deserialize<{{className}}>(json)!;
                    }
                """);
            }

            sb.AppendLine("}");

            context.AddSource("GeneratedSerialization.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is ClassDeclarationSyntax c &&
                    c.AttributeLists.Any(a => a.Attributes.Any(attr =>
                        attr.Name.ToString().Contains("GenerateSerializer"))))
                {
                    Candidates.Add(c);
                }
            }
        }
    }

    [Generator]
    public sealed class ErrorCodeGenerator : ISourceGenerator
    {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not Receiver receiver)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace VisionaryCoder.Errors.Generated {");

            foreach (var enumDecl in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(enumDecl.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(enumDecl) as INamedTypeSymbol;
                if (symbol is null) continue;

                var enumName = symbol.Name;

                sb.AppendLine($"public static class {enumName}_Codes {{");

                foreach (var member in symbol.GetMembers().OfType<IFieldSymbol>())
                {
                    if (member.ConstantValue is null) continue;
                    sb.AppendLine($"    public const int {member.Name} = {member.ConstantValue};");
                }

                sb.AppendLine("}");
            }

            sb.AppendLine("}");

            context.AddSource("GeneratedErrorCodes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<EnumDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is EnumDeclarationSyntax e &&
                    e.AttributeLists.Any(a => a.Attributes.Any(attr =>
                        attr.Name.ToString().Contains("GenerateErrorCodes"))))
                {
                    Candidates.Add(e);
                }
            }
        }
    }

    [Generator]
    public sealed class ResourceLocalizationGenerator : ISourceGenerator
    {
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new Receiver());
    }

    public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not Receiver receiver)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace VisionaryCoder.Localization.Generated {");

            foreach (var cls in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(cls.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(cls) as INamedTypeSymbol;
                if (symbol is null) continue;

                var className = symbol.Name;

                sb.AppendLine($$"""
                    public static class {{className}}_Localization
                    {
                        public static string Get(string key, System.Globalization.CultureInfo? culture = null)
                        {
                            culture ??= System.Globalization.CultureInfo.CurrentUICulture;
                            return $"{className}:{culture.TwoLetterISOLanguageName}:{key}";
                        }
                    }
                """);
            }

            sb.AppendLine("}");

            context.AddSource("GeneratedLocalization.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> Candidates { get; } = new();

            public void OnVisitSyntaxNode(SyntaxNode node)
            {
                if (node is ClassDeclarationSyntax c &&
                    c.AttributeLists.Any(a => a.Attributes.Any(attr =>
                        attr.Name.ToString().Contains("GenerateLocalization"))))
                {
                    Candidates.Add(c);
                }
            }
        }
    }

