namespace VisionaryCoder.Generators.Common
{
    public sealed class GeneratorOptions
    {
        public string? RootNamespace { get; set; }
        public string RepositoryNamespace { get; set; } = "Repositories";
        public string ValidatorNamespace { get; set; } = "Validators";
        public string DtoNamespace { get; set; } = "Dtos";
        public bool NullableEnabled { get; set; } = true;
        public bool FileScopedNamespaces { get; set; } = true;
        public bool EmitAutoGeneratedHeader { get; set; } = true;
        public bool GenerateRepositoryImplementations { get; set; } = true;
        public bool EmitServiceRegistration { get; set; } = true;
        public bool GenerateMediatorHandlers { get; set; } = false;
        public string? JwtIssuer { get; set; }
        public string? JwtAudience { get; set; }
        public string JwtSecretKeyConfigPath { get; set; } = "Jwt:SecretKey";
    }
}