using System.Text;

namespace VisionaryCoder.Generators.Common;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class ValidatorGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.GenerateValidatorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static ValidatorModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[index: 0];
        var suffix = attr.NamedArguments.FirstOrDefault(predicate: a => a.Key == "ClassSuffix").Value.Value as string ?? "Validator";
        var useAnnotations = attr.NamedArguments.FirstOrDefault(predicate: a => a.Key == "UseDataAnnotations").Value.Value is not false;
        var properties = typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(predicate: p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .Select(selector: p => new PropertyModel(Name: p.Name, TypeName: p.Type.ToDisplayString(), IsRequired: p.IsRequired))
            .ToArray();
        return new ValidatorModel(EntityName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString(), Suffix: suffix, UseDataAnnotations: useAnnotations, Properties: properties);
    }

    private static void Execute(SourceProductionContext ctx, ValidatorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Validators;");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated validator for <see cref=\"{model.EntityName}\"/>.</summary>");
        sb.AppendLine(value: $"public sealed class {model.EntityName}{model.Suffix}");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    /// <summary>Validates the provided instance and returns a result indicating success or failure.</summary>");
        sb.AppendLine(value: $"    public ValidationResult Validate({model.EntityName} instance)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        var errors = new List<string>();");
        foreach (var prop in model.Properties)
        {
            if (prop.TypeName == "string" || prop.TypeName == "string?")
                sb.AppendLine(value: $"        if (string.IsNullOrWhiteSpace(instance.{prop.Name})) errors.Add(\"\"{prop.Name} is required.\");");
        }
        sb.AppendLine(value: "        return new ValidationResult(errors.Count == 0, errors);");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.EntityName}{model.Suffix}.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record PropertyModel(string Name, string TypeName, bool IsRequired);
    private sealed record ValidatorModel(string EntityName, string Namespace, string Suffix, bool UseDataAnnotations, PropertyModel[] Properties);
}