using System.Text;

namespace VisionaryCoder.Generators.Common.Builders;

public sealed class FileBuilder
{
    private readonly SourceBuilder _sb = new SourceBuilder(new StringBuilder());

    public FileBuilder Header()
    {
        _sb.Line("// <auto-generated />");
        return this;
    }

    public FileBuilder Namespace(string ns)
    {
        _sb.Line($"namespace {ns};");
        _sb.Line();
        return this;
    }

    public FileBuilder Line(string text = "")
    {
        _sb.Line(text);
        return this;
    }

    public override string ToString()
    {
        return _sb.ToString();
    }
}