using System.Text;

namespace VisionaryCoder.Generators.Data;

/// <summary>
/// Generates auditable aggregate root classes for change tracking and auditing.
/// Targets classes decorated with [VcAuditableAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AuditableGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcAuditableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static AuditableModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new AuditableModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, AuditableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auditable wrapper for {model.EntityName} with change tracking.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.EntityName}Audit");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly List<AuditEntry> _auditTrail = new();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the audit trail of changes.</summary>");
        sb.AppendLine("    public IReadOnlyList<AuditEntry> AuditTrail => _auditTrail.AsReadOnly();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Records a change in the audit trail.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"propertyName\">Name of the changed property.</param>");
        sb.AppendLine("    /// <param name=\"oldValue\">The previous value.</param>");
        sb.AppendLine("    /// <param name=\"newValue\">The new value.</param>");
        sb.AppendLine("    public void RecordChange(string propertyName, object? oldValue, object? newValue)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(propertyName))");
        sb.AppendLine("            throw new ArgumentException(\"Property name cannot be null or empty.\", nameof(propertyName));");
        sb.AppendLine();
        sb.AppendLine("        var entry = new AuditEntry(propertyName, oldValue, newValue, DateTime.UtcNow);");
        sb.AppendLine("        _auditTrail.Add(entry);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Clears the audit trail.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void ClearAuditTrail() => _auditTrail.Clear();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the audit history for a specific property.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"propertyName\">Name of the property.</param>");
        sb.AppendLine("    /// <returns>List of audit entries for the property.</returns>");
        sb.AppendLine("    public IReadOnlyList<AuditEntry> GetPropertyHistory(string propertyName)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _auditTrail.Where(e => e.PropertyName == propertyName).ToList().AsReadOnly();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Represents a single audit entry.</summary>");
        sb.AppendLine("    public sealed class AuditEntry");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Gets the changed property name.</summary>");
        sb.AppendLine("        public string PropertyName { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Gets the previous value.</summary>");
        sb.AppendLine("        public object? OldValue { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Gets the new value.</summary>");
        sb.AppendLine("        public object? NewValue { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Gets the timestamp of the change.</summary>");
        sb.AppendLine("        public DateTime ChangedAt { get; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Initializes a new audit entry.</summary>");
        sb.AppendLine("        public AuditEntry(string propertyName, object? oldValue, object? newValue, DateTime changedAt)");
        sb.AppendLine("        {");
        sb.AppendLine("            PropertyName = propertyName;");
        sb.AppendLine("            OldValue = oldValue;");
        sb.AppendLine("            NewValue = newValue;");
        sb.AppendLine("            ChangedAt = changedAt;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EntityName}Audit.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record AuditableModel(string EntityName, string Namespace);
}
