using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates cacheable aggregate root classes for distributed caching patterns.
/// Targets classes decorated with [VcCacheableAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CacheableGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcCacheableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static CacheableModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new CacheableModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, CacheableModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Cacheable wrapper for {model.EntityName} aggregate root.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.EntityName}Cache");
        sb.AppendLine("{");
        sb.AppendLine($"    private {model.EntityName}? _cachedInstance;");
        sb.AppendLine("    private DateTime _cachedAt;");
        sb.AppendLine("    private TimeSpan _cacheDuration;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the cached instance.</summary>");
        sb.AppendLine($"    public {model.EntityName}? CachedInstance => _cachedInstance;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the cache creation timestamp.</summary>");
        sb.AppendLine("    public DateTime CachedAt => _cachedAt;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets a value indicating whether the cache is valid.</summary>");
        sb.AppendLine("    public bool IsValid => DateTime.UtcNow - _cachedAt < _cacheDuration;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Stores an instance of {model.EntityName} in the cache.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"instance\">The {model.EntityName} to cache.</param>");
        sb.AppendLine("    /// <param name=\"duration\">The cache duration.</param>");
        sb.AppendLine($"    public void Cache({model.EntityName} instance, TimeSpan duration)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (instance == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(instance), \"Instance to cache cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine("        _cachedInstance = instance;");
        sb.AppendLine("        _cachedAt = DateTime.UtcNow;");
        sb.AppendLine("        _cacheDuration = duration;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Invalidates the current cache.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void Invalidate()");
        sb.AppendLine("    {");
        sb.AppendLine("        _cachedInstance = null;");
        sb.AppendLine("        _cachedAt = DateTime.MinValue;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Retrieves the cached instance if valid, otherwise returns null.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <returns>The cached {model.EntityName} instance or null if cache is invalid.</returns>");
        sb.AppendLine($"    public {model.EntityName}? GetIfValid()");
        sb.AppendLine("    {");
        sb.AppendLine("        return IsValid ? _cachedInstance : null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EntityName}Cache.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record CacheableModel(string EntityName, string Namespace);
}
