using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates ICommandHandler{TCommand} implementations for command handler classes.
/// Targets classes decorated with [VcCommandHandlerAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class CommandHandlerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcCommandHandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static CommandHandlerModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new CommandHandlerModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, CommandHandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated command handler interface for {model.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial interface ICommandHandler{model.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Handles the command for {model.ClassName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    Task<CommandResult> Handle(object command, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Result of executing a command handler.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class CommandResult");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets a value indicating whether the command executed successfully.</summary>");
        sb.AppendLine("    public bool IsSuccess { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the error message if execution failed.</summary>");
        sb.AppendLine("    public string? ErrorMessage { get; }");
        sb.AppendLine();
        sb.AppendLine("    private CommandResult(bool isSuccess, string? errorMessage = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        IsSuccess = isSuccess;");
        sb.AppendLine("        ErrorMessage = errorMessage;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a successful command result.</summary>");
        sb.AppendLine("    public static CommandResult Success() => new(true);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a failed command result with an error message.</summary>");
        sb.AppendLine("    public static CommandResult Failure(string errorMessage) => new(false, errorMessage);");
        sb.AppendLine("}");

        ctx.AddSource($"ICommandHandler{model.ClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record CommandHandlerModel(string ClassName, string Namespace);
}
