using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates Data Transfer Object (DTO) classes from entity classes.
/// Targets classes decorated with [VcDtoAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DtoGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcDtoAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static DtoModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new DtoModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, DtoModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Data Transfer Object for {model.EntityName} entity.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.EntityName}Dto");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets or sets the entity ID.</summary>");
        sb.AppendLine("    public Guid Id { get; set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets or sets the creation timestamp.</summary>");
        sb.AppendLine("    public DateTime CreatedAt { get; set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets or sets the last modification timestamp.</summary>");
        sb.AppendLine("    public DateTime? UpdatedAt { get; set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets or sets the entity version.</summary>");
        sb.AppendLine("    public int Version { get; set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Initializes a new instance of the DTO class.</summary>");
        sb.AppendLine($"    public {model.EntityName}Dto()");
        sb.AppendLine("    {");
        sb.AppendLine("        Id = Guid.Empty;");
        sb.AppendLine("        CreatedAt = DateTime.UtcNow;");
        sb.AppendLine("        UpdatedAt = null;");
        sb.AppendLine("        Version = 0;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EntityName}Dto.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record DtoModel(string EntityName, string Namespace);
}