using System.Text;

namespace VisionaryCoder.Generators.Data;

/// <summary>
/// Generates Data Transfer Object (DTO) classes from entity classes.
/// Targets classes decorated with [VcDtoAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class DtoGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcDtoAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static DtoModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new DtoModel(
            EntityName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, DtoModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Data Transfer Object for {model.EntityName} entity.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.EntityName}Dto");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Gets or sets the entity ID.</summary>");
        sb.AppendLine(value: "    public Guid Id { get; set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets or sets the creation timestamp.</summary>");
        sb.AppendLine(value: "    public DateTime CreatedAt { get; set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets or sets the last modification timestamp.</summary>");
        sb.AppendLine(value: "    public DateTime? UpdatedAt { get; set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets or sets the entity version.</summary>");
        sb.AppendLine(value: "    public int Version { get; set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Initializes a new instance of the DTO class.</summary>");
        sb.AppendLine(value: $"    public {model.EntityName}Dto()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        Id = Guid.Empty;");
        sb.AppendLine(value: "        CreatedAt = DateTime.UtcNow;");
        sb.AppendLine(value: "        UpdatedAt = null;");
        sb.AppendLine(value: "        Version = 0;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.EntityName}Dto.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record DtoModel(string EntityName, string Namespace);
}