using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates mapper classes for converting between entities and DTOs.
/// Targets classes decorated with [VcMapperAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MapperGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcMapperAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static MapperModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new MapperModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, MapperModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Mapper for converting between {model.EntityName} entity and DTO.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.EntityName}Mapper");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Maps {model.EntityName}Dto to {model.EntityName} entity.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"dto\">The DTO to map.</param>");
        sb.AppendLine("    /// <returns>The mapped entity.</returns>");
        sb.AppendLine($"    public static {model.EntityName} DtoToEntity({model.EntityName}Dto dto)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (dto == null) throw new ArgumentNullException(nameof(dto));");
        sb.AppendLine();
        sb.AppendLine($"        return new {model.EntityName}");
        sb.AppendLine("        {");
        sb.AppendLine("            Id = dto.Id,");
        sb.AppendLine("            CreatedAt = dto.CreatedAt,");
        sb.AppendLine("            UpdatedAt = dto.UpdatedAt,");
        sb.AppendLine("            Version = dto.Version");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Maps {model.EntityName} entity to {model.EntityName}Dto.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"entity\">The entity to map.</param>");
        sb.AppendLine("    /// <returns>The mapped DTO.</returns>");
        sb.AppendLine($"    public static {model.EntityName}Dto EntityToDto({model.EntityName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (entity == null) throw new ArgumentNullException(nameof(entity));");
        sb.AppendLine();
        sb.AppendLine($"        return new {model.EntityName}Dto");
        sb.AppendLine("        {");
        sb.AppendLine("            Id = entity.Id,");
        sb.AppendLine("            CreatedAt = entity.CreatedAt,");
        sb.AppendLine("            UpdatedAt = entity.UpdatedAt,");
        sb.AppendLine("            Version = entity.Version");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Maps a collection of {model.EntityName}Dto to {model.EntityName} entities.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"dtos\">The DTOs to map.</param>");
        sb.AppendLine("    /// <returns>The mapped entities.</returns>");
        sb.AppendLine($"    public static IEnumerable<{model.EntityName}> DtosToEntities(IEnumerable<{model.EntityName}Dto> dtos)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (dtos == null) throw new ArgumentNullException(nameof(dtos));");
        sb.AppendLine("        return dtos.Select(DtoToEntity);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Maps a collection of {model.EntityName} entities to {model.EntityName}Dto.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"entities\">The entities to map.</param>");
        sb.AppendLine("    /// <returns>The mapped DTOs.</returns>");
        sb.AppendLine($"    public static IEnumerable<{model.EntityName}Dto> EntitiesToDtos(IEnumerable<{model.EntityName}> entities)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (entities == null) throw new ArgumentNullException(nameof(entities));");
        sb.AppendLine("        return entities.Select(EntityToDto);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EntityName}Mapper.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record MapperModel(string EntityName, string Namespace);
}
