using System.Text;

namespace VisionaryCoder.Generators.Data;

/// <summary>
/// Generates mapper classes for converting between entities and DTOs.
/// Targets classes decorated with [VcMapperAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class MapperGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcMapperAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static MapperModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new MapperModel(
            EntityName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, MapperModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Mapper for converting between {model.EntityName} entity and DTO.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.EntityName}Mapper");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Maps {model.EntityName}Dto to {model.EntityName} entity.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"dto\">The DTO to map.</param>");
        sb.AppendLine(value: "    /// <returns>The mapped entity.</returns>");
        sb.AppendLine(value: $"    public static {model.EntityName} DtoToEntity({model.EntityName}Dto dto)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (dto == null) throw new ArgumentNullException(nameof(dto));");
        sb.AppendLine();
        sb.AppendLine(value: $"        return new {model.EntityName}");
        sb.AppendLine(value: "        {");
        sb.AppendLine(value: "            Id = dto.Id,");
        sb.AppendLine(value: "            CreatedAt = dto.CreatedAt,");
        sb.AppendLine(value: "            UpdatedAt = dto.UpdatedAt,");
        sb.AppendLine(value: "            Version = dto.Version");
        sb.AppendLine(value: "        };");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Maps {model.EntityName} entity to {model.EntityName}Dto.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    /// <param name=\"entity\">The entity to map.</param>");
        sb.AppendLine(value: "    /// <returns>The mapped DTO.</returns>");
        sb.AppendLine(value: $"    public static {model.EntityName}Dto EntityToDto({model.EntityName} entity)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (entity == null) throw new ArgumentNullException(nameof(entity));");
        sb.AppendLine();
        sb.AppendLine(value: $"        return new {model.EntityName}Dto");
        sb.AppendLine(value: "        {");
        sb.AppendLine(value: "            Id = entity.Id,");
        sb.AppendLine(value: "            CreatedAt = entity.CreatedAt,");
        sb.AppendLine(value: "            UpdatedAt = entity.UpdatedAt,");
        sb.AppendLine(value: "            Version = entity.Version");
        sb.AppendLine(value: "        };");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Maps a collection of {model.EntityName}Dto to {model.EntityName} entities.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"dtos\">The DTOs to map.</param>");
        sb.AppendLine(value: "    /// <returns>The mapped entities.</returns>");
        sb.AppendLine(value: $"    public static IEnumerable<{model.EntityName}> DtosToEntities(IEnumerable<{model.EntityName}Dto> dtos)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (dtos == null) throw new ArgumentNullException(nameof(dtos));");
        sb.AppendLine(value: "        return dtos.Select(DtoToEntity);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Maps a collection of {model.EntityName} entities to {model.EntityName}Dto.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    /// <param name=\"entities\">The entities to map.</param>");
        sb.AppendLine(value: "    /// <returns>The mapped DTOs.</returns>");
        sb.AppendLine(value: $"    public static IEnumerable<{model.EntityName}Dto> EntitiesToDtos(IEnumerable<{model.EntityName}> entities)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (entities == null) throw new ArgumentNullException(nameof(entities));");
        sb.AppendLine(value: "        return entities.Select(EntityToDto);");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.EntityName}Mapper.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record MapperModel(string EntityName, string Namespace);
}
