using System.Text;

namespace VisionaryCoder.Generators.Data;

/// <summary>
/// Generates message contract classes for messaging/event-driven architectures.
/// Targets classes decorated with [VcMessageContractAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class MessageContractGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcMessageContractAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static MessageContractModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new MessageContractModel(
            MessageName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, MessageContractModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Message contract for {model.MessageName} messaging.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.MessageName}Contract");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Gets the unique message identifier.</summary>");
        sb.AppendLine(value: "    public Guid MessageId { get; private set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the message correlation identifier.</summary>");
        sb.AppendLine(value: "    public Guid CorrelationId { get; private set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the message creation timestamp.</summary>");
        sb.AppendLine(value: "    public DateTime CreatedAt { get; private set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the message type name.</summary>");
        sb.AppendLine(value: "    public string MessageType { get; private set; } = string.Empty;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the message version.</summary>");
        sb.AppendLine(value: "    public int Version { get; private set; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the message payload as JSON.</summary>");
        sb.AppendLine(value: "    public string Payload { get; private set; } = string.Empty;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Initializes a new instance of the message contract.</summary>");
        sb.AppendLine(value: $"    public {model.MessageName}Contract()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        MessageId = Guid.NewGuid();");
        sb.AppendLine(value: "        CorrelationId = Guid.NewGuid();");
        sb.AppendLine(value: "        CreatedAt = DateTime.UtcNow;");
        sb.AppendLine(value: $"        MessageType = \"{model.MessageName}\";");
        sb.AppendLine(value: "        Version = 1;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Creates a new message contract with the specified payload.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"payload\">The message payload as JSON.</param>");
        sb.AppendLine(value: "    /// <returns>A new message contract instance.</returns>");
        sb.AppendLine(value: $"    public static {model.MessageName}Contract Create(string payload)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (string.IsNullOrWhiteSpace(payload))");
        sb.AppendLine(value: "            throw new ArgumentException(\"Payload cannot be null or empty.\", nameof(payload));");
        sb.AppendLine(value: $"        var contract = new {model.MessageName}Contract");
        sb.AppendLine(value: "        {");
        sb.AppendLine(value: "            Payload = payload");
        sb.AppendLine(value: "        };");
        sb.AppendLine(value: "        return contract;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Creates a copy of this message with a new correlation identifier.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <returns>A new message contract with new correlation.</returns>");
        sb.AppendLine(value: $"    public {model.MessageName}Contract WithNewCorrelation()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: $"        var copy = new {model.MessageName}Contract");
        sb.AppendLine(value: "        {");
        sb.AppendLine(value: "            CorrelationId = Guid.NewGuid(),");
        sb.AppendLine(value: "            CreatedAt = DateTime.UtcNow,");
        sb.AppendLine(value: "            Payload = Payload");
        sb.AppendLine(value: "        };");
        sb.AppendLine(value: "        return copy;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.MessageName}Contract.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record MessageContractModel(string MessageName, string Namespace);
}
