using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates message contract classes for messaging/event-driven architectures.
/// Targets classes decorated with [VcMessageContractAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MessageContractGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcMessageContractAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static MessageContractModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new MessageContractModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, MessageContractModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Message contract for {model.MessageName} messaging.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.MessageName}Contract");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets the unique message identifier.</summary>");
        sb.AppendLine("    public Guid MessageId { get; private set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the message correlation identifier.</summary>");
        sb.AppendLine("    public Guid CorrelationId { get; private set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the message creation timestamp.</summary>");
        sb.AppendLine("    public DateTime CreatedAt { get; private set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the message type name.</summary>");
        sb.AppendLine("    public string MessageType { get; private set; } = string.Empty;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the message version.</summary>");
        sb.AppendLine("    public int Version { get; private set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the message payload as JSON.</summary>");
        sb.AppendLine("    public string Payload { get; private set; } = string.Empty;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Initializes a new instance of the message contract.</summary>");
        sb.AppendLine($"    public {model.MessageName}Contract()");
        sb.AppendLine("    {");
        sb.AppendLine("        MessageId = Guid.NewGuid();");
        sb.AppendLine("        CorrelationId = Guid.NewGuid();");
        sb.AppendLine("        CreatedAt = DateTime.UtcNow;");
        sb.AppendLine($"        MessageType = \"{model.MessageName}\";");
        sb.AppendLine("        Version = 1;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a new message contract with the specified payload.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"payload\">The message payload as JSON.</param>");
        sb.AppendLine("    /// <returns>A new message contract instance.</returns>");
        sb.AppendLine($"    public static {model.MessageName}Contract Create(string payload)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(payload))");
        sb.AppendLine("            throw new ArgumentException(\"Payload cannot be null or empty.\", nameof(payload));");
        sb.AppendLine($"        var contract = new {model.MessageName}Contract");
        sb.AppendLine("        {");
        sb.AppendLine("            Payload = payload");
        sb.AppendLine("        };");
        sb.AppendLine("        return contract;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a copy of this message with a new correlation identifier.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <returns>A new message contract with new correlation.</returns>");
        sb.AppendLine($"    public {model.MessageName}Contract WithNewCorrelation()");
        sb.AppendLine("    {");
        sb.AppendLine($"        var copy = new {model.MessageName}Contract");
        sb.AppendLine("        {");
        sb.AppendLine("            CorrelationId = Guid.NewGuid(),");
        sb.AppendLine("            CreatedAt = DateTime.UtcNow,");
        sb.AppendLine("            Payload = Payload");
        sb.AppendLine("        };");
        sb.AppendLine("        return copy;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.MessageName}Contract.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record MessageContractModel(string MessageName, string Namespace);
}
