using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates IQueryHandler{TQuery} implementations for query handler classes.
/// Targets classes decorated with [VcQueryHandlerAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class QueryHandlerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcQueryHandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static QueryHandlerModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new QueryHandlerModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, QueryHandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated query handler interface for {model.ClassName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial interface IQueryHandler{model.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Executes the query for {model.ClassName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"query\">The query object containing parameters.</param>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token for the operation.</param>");
        sb.AppendLine("    /// <returns>A task representing the asynchronous query operation.</returns>");
        sb.AppendLine($"    Task<QueryResult> Execute(object query, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generic result of executing a query handler.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <typeparam name=\"TData\">The type of data returned by the query.</typeparam>");
        sb.AppendLine("public sealed class QueryResult<TData>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets a value indicating whether the query executed successfully.</summary>");
        sb.AppendLine("    public bool IsSuccess { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the returned data if the query was successful.</summary>");
        sb.AppendLine("    public TData? Data { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the error message if execution failed.</summary>");
        sb.AppendLine("    public string? ErrorMessage { get; }");
        sb.AppendLine();
        sb.AppendLine("    private QueryResult(bool isSuccess, TData? data = default, string? errorMessage = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        IsSuccess = isSuccess;");
        sb.AppendLine("        Data = data;");
        sb.AppendLine("        ErrorMessage = errorMessage;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a successful query result with data.</summary>");
        sb.AppendLine("    public static QueryResult<TData> Success(TData data) => new(true, data);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a failed query result with an error message.</summary>");
        sb.AppendLine("    public static QueryResult<TData> Failure(string errorMessage) => new(false, errorMessage: errorMessage);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Non-generic result of executing a query handler.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class QueryResult");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets a value indicating whether the query executed successfully.</summary>");
        sb.AppendLine("    public bool IsSuccess { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the error message if execution failed.</summary>");
        sb.AppendLine("    public string? ErrorMessage { get; }");
        sb.AppendLine();
        sb.AppendLine("    private QueryResult(bool isSuccess, string? errorMessage = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        IsSuccess = isSuccess;");
        sb.AppendLine("        ErrorMessage = errorMessage;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a successful query result.</summary>");
        sb.AppendLine("    public static QueryResult Success() => new(true);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a failed query result with an error message.</summary>");
        sb.AppendLine("    public static QueryResult Failure(string errorMessage) => new(false, errorMessage);");
        sb.AppendLine("}");

        ctx.AddSource($"IQueryHandler{model.ClassName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record QueryHandlerModel(string ClassName, string Namespace);
}
