using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class RepositoryGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.GenerateRepositoryAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static RepositoryModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[0];
        var softDelete = attr.NamedArguments.FirstOrDefault(a => a.Key == "SoftDelete").Value.Value is true;
        var paginated = attr.NamedArguments.FirstOrDefault(a => a.Key == "Paginated").Value.Value is not false;
        var asyncOnly = attr.NamedArguments.FirstOrDefault(a => a.Key == "AsyncOnly").Value.Value is not false;
        return new RepositoryModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), softDelete, paginated, asyncOnly);
    }

    private static void Execute(SourceProductionContext ctx, RepositoryModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Repositories;");
        sb.AppendLine();
        sb.AppendLine($"public interface I{model.EntityName}Repository");
        sb.AppendLine("{");
        sb.AppendLine($"    Task<{model.EntityName}?> GetByIdAsync(Guid id, CancellationToken ct = default);");
        sb.AppendLine($"    Task<IReadOnlyList<{model.EntityName}>> GetAllAsync(CancellationToken ct = default);");
        if (model.Paginated)
            sb.AppendLine($"    Task<PagedResult<{model.EntityName}>> GetPagedAsync(int page, int size, CancellationToken ct = default);");
        sb.AppendLine($"    Task<{model.EntityName}> AddAsync({model.EntityName} entity, CancellationToken ct = default);");
        sb.AppendLine($"    Task UpdateAsync({model.EntityName} entity, CancellationToken ct = default);");
        sb.AppendLine(model.SoftDelete
            ? $"    Task SoftDeleteAsync(Guid id, CancellationToken ct = default);"
            : $"    Task DeleteAsync(Guid id, CancellationToken ct = default);");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EntityName}Repository.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record RepositoryModel(string EntityName, string Namespace, bool SoftDelete, bool Paginated, bool AsyncOnly);
}