using System.Text;

namespace VisionaryCoder.Generators.Data;

/// <summary>
/// Generates repository interfaces for aggregate root classes.
/// Targets classes decorated with [VcRepositoryAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class RepositoryGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcRepositoryAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static RepositoryModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new RepositoryModel(
            AggregateRootName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, RepositoryModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Repository interface for {model.AggregateRootName} aggregate root.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public interface I{model.AggregateRootName}Repository");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Finds a {model.AggregateRootName} by ID.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"id\">The aggregate ID.</param>");
        sb.AppendLine(value: "    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine(value: "    /// <returns>The aggregate if found; null otherwise.</returns>");
        sb.AppendLine(value: $"    Task<{model.AggregateRootName}?> FindByIdAsync(Guid id, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Gets all {model.AggregateRootName} aggregates.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine(value: "    /// <returns>Enumerable of all aggregates.</returns>");
        sb.AppendLine(value: $"    Task<IEnumerable<{model.AggregateRootName}>> GetAllAsync(CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Adds a {model.AggregateRootName} to the repository.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"aggregate\">The aggregate to add.</param>");
        sb.AppendLine(value: "    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine(value: "    /// <returns>Task representing the asynchronous operation.</returns>");
        sb.AppendLine(value: $"    Task AddAsync({model.AggregateRootName} aggregate, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Updates a {model.AggregateRootName} in the repository.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"aggregate\">The aggregate to update.</param>");
        sb.AppendLine(value: "    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine(value: "    /// <returns>Task representing the asynchronous operation.</returns>");
        sb.AppendLine(value: $"    Task UpdateAsync({model.AggregateRootName} aggregate, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Deletes a {model.AggregateRootName} from the repository.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"id\">The aggregate ID.</param>");
        sb.AppendLine(value: "    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine(value: "    /// <returns>Task representing the asynchronous operation.</returns>");
        sb.AppendLine(value: "    Task DeleteAsync(Guid id, CancellationToken cancellationToken = default);");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"I{model.AggregateRootName}Repository.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record RepositoryModel(string AggregateRootName, string Namespace);
}