using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates repository interfaces for aggregate root classes.
/// Targets classes decorated with [VcRepositoryAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RepositoryGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Data.VcRepositoryAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static RepositoryModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new RepositoryModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, RepositoryModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Repository interface for {model.AggregateRootName} aggregate root.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public interface I{model.AggregateRootName}Repository");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Finds a {model.AggregateRootName} by ID.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"id\">The aggregate ID.</param>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("    /// <returns>The aggregate if found; null otherwise.</returns>");
        sb.AppendLine($"    Task<{model.AggregateRootName}?> FindByIdAsync(Guid id, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Gets all {model.AggregateRootName} aggregates.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("    /// <returns>Enumerable of all aggregates.</returns>");
        sb.AppendLine($"    Task<IEnumerable<{model.AggregateRootName}>> GetAllAsync(CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Adds a {model.AggregateRootName} to the repository.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"aggregate\">The aggregate to add.</param>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("    /// <returns>Task representing the asynchronous operation.</returns>");
        sb.AppendLine($"    Task AddAsync({model.AggregateRootName} aggregate, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Updates a {model.AggregateRootName} in the repository.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"aggregate\">The aggregate to update.</param>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("    /// <returns>Task representing the asynchronous operation.</returns>");
        sb.AppendLine($"    Task UpdateAsync({model.AggregateRootName} aggregate, CancellationToken cancellationToken = default);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Deletes a {model.AggregateRootName} from the repository.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"id\">The aggregate ID.</param>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("    /// <returns>Task representing the asynchronous operation.</returns>");
        sb.AppendLine("    Task DeleteAsync(Guid id, CancellationToken cancellationToken = default);");
        sb.AppendLine("}");

        ctx.AddSource($"I{model.AggregateRootName}Repository.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record RepositoryModel(string AggregateRootName, string Namespace);
}