using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class LoggerMessageGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Attributes.VcLoggingContextAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static LoggerMessageModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var publicMethods = typeSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.DeclaredAccessibility == Accessibility.Public &&
                        m.MethodKind == MethodKind.Ordinary &&
                        !m.IsStatic)
            .Select(m => m.Name)
            .ToList();

        return new LoggerMessageModel(typeSymbol.Name, ns, publicMethods);
    }

    private static void Execute(SourceProductionContext ctx, LoggerMessageModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Auto-generated source-generated log methods for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public static partial class {model.TypeName}Log");
        sb.AppendLine("{");
        sb.AppendLine("    [LoggerMessage(EventId = 1000, Level = LogLevel.Information, Message = \"{TypeName} started\")]");
        sb.AppendLine($"    public static partial void Started(this ILogger logger, string typeName);");
        sb.AppendLine();
        sb.AppendLine("    [LoggerMessage(EventId = 1001, Level = LogLevel.Information, Message = \"{TypeName} completed in {ElapsedMs}ms\")]");
        sb.AppendLine($"    public static partial void Completed(this ILogger logger, string typeName, long elapsedMs);");
        sb.AppendLine();
        sb.AppendLine("    [LoggerMessage(EventId = 1002, Level = LogLevel.Error, Message = \"{TypeName} failed with error: {Message}\")]");
        sb.AppendLine($"    public static partial void Failed(this ILogger logger, string typeName, string message, Exception exception);");

        var eventId = 1003;
        foreach (var methodName in model.MethodNames)
        {
            sb.AppendLine();
            sb.AppendLine($"    [LoggerMessage(EventId = {eventId++}, Level = LogLevel.Debug, Message = \"{model.TypeName}.{methodName} called\")]");
            sb.AppendLine($"    public static partial void {methodName}Called(this ILogger logger);");
        }

        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}Log.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record LoggerMessageModel(string TypeName, string Namespace, List<string> MethodNames);
}
