using System.Text;

namespace VisionaryCoder.Generators.Observability;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class LoggerMessageGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Attributes.VcLoggingContextAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static LoggerMessageModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var publicMethods = typeSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(predicate: m => m.DeclaredAccessibility == Accessibility.Public &&
                                   m.MethodKind == MethodKind.Ordinary &&
                                   !m.IsStatic)
            .Select(selector: m => m.Name)
            .ToList();

        return new LoggerMessageModel(TypeName: typeSymbol.Name, Namespace: ns, MethodNames: publicMethods);
    }

    private static void Execute(SourceProductionContext ctx, LoggerMessageModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: "using Microsoft.Extensions.Logging;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(value: model.Namespace))
        {
            sb.AppendLine(value: $"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine(value: $"/// <summary>Auto-generated source-generated log methods for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine(value: $"public static partial class {model.TypeName}Log");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    [LoggerMessage(EventId = 1000, Level = LogLevel.Information, Message = \"{TypeName} started\")]");
        sb.AppendLine(value: $"    public static partial void Started(this ILogger logger, string typeName);");
        sb.AppendLine();
        sb.AppendLine(value: "    [LoggerMessage(EventId = 1001, Level = LogLevel.Information, Message = \"{TypeName} completed in {ElapsedMs}ms\")]");
        sb.AppendLine(value: $"    public static partial void Completed(this ILogger logger, string typeName, long elapsedMs);");
        sb.AppendLine();
        sb.AppendLine(value: "    [LoggerMessage(EventId = 1002, Level = LogLevel.Error, Message = \"{TypeName} failed with error: {Message}\")]");
        sb.AppendLine(value: $"    public static partial void Failed(this ILogger logger, string typeName, string message, Exception exception);");

        var eventId = 1003;
        foreach (var methodName in model.MethodNames)
        {
            sb.AppendLine();
            sb.AppendLine(value: $"    [LoggerMessage(EventId = {eventId++}, Level = LogLevel.Debug, Message = \"{model.TypeName}.{methodName} called\")]");
            sb.AppendLine(value: $"    public static partial void {methodName}Called(this ILogger logger);");
        }

        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.TypeName}Log.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record LoggerMessageModel(string TypeName, string Namespace, List<string> MethodNames);
}
