using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class TelemetryGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.TraceAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static TelemetryModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IMethodSymbol methodSymbol) return null;
        return new TelemetryModel(methodSymbol.Name, methodSymbol.ContainingType.Name, methodSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, TelemetryModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated telemetry instrumentation hooks for <see cref=\"{{model.TypeName}}\"/>.</summary>");
        sb.AppendLine($"public partial class {model.TypeName}");
        sb.AppendLine("{");
        sb.AppendLine("    // Telemetry wrapper for: " + model.MethodName);
        sb.AppendLine("    //");
        sb.AppendLine("    // This partial method should be implemented to:");
        sb.AppendLine("    // 1. Start System.Diagnostics.Activity");
        sb.AppendLine("    // 2. Log method entry");
        sb.AppendLine("    // 3. Call original method");
        sb.AppendLine("    // 4. Log method exit");
        sb.AppendLine("    // 5. Capture exceptions");
        sb.AppendLine("    //");
        sb.AppendLine($"    partial void On{model.MethodName}Starting();");
        sb.AppendLine($"    partial void On{model.MethodName}Completed();");
        sb.AppendLine($"    partial void On{model.MethodName}Failed(Exception ex);");
        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}Telemetry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record TelemetryModel(string MethodName, string TypeName, string Namespace);
}
