using System.Text;

namespace VisionaryCoder.Generators.Observability;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class TelemetryGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.TraceAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static TelemetryModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IMethodSymbol methodSymbol) return null;
        return new TelemetryModel(MethodName: methodSymbol.Name, TypeName: methodSymbol.ContainingType.Name, Namespace: methodSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, TelemetryModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated telemetry instrumentation hooks for <see cref=\"{{model.TypeName}}\"/>.</summary>");
        sb.AppendLine(value: $"public partial class {model.TypeName}");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    // Telemetry wrapper for: " + model.MethodName);
        sb.AppendLine(value: "    //");
        sb.AppendLine(value: "    // This partial method should be implemented to:");
        sb.AppendLine(value: "    // 1. Start System.Diagnostics.Activity");
        sb.AppendLine(value: "    // 2. Log method entry");
        sb.AppendLine(value: "    // 3. Call original method");
        sb.AppendLine(value: "    // 4. Log method exit");
        sb.AppendLine(value: "    // 5. Capture exceptions");
        sb.AppendLine(value: "    //");
        sb.AppendLine(value: $"    partial void On{model.MethodName}Starting();");
        sb.AppendLine(value: $"    partial void On{model.MethodName}Completed();");
        sb.AppendLine(value: $"    partial void On{model.MethodName}Failed(Exception ex);");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.TypeName}Telemetry.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record TelemetryModel(string MethodName, string TypeName, string Namespace);
}
