using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class DtoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "VisionaryCoder.Tooling.Shared.Attributes.GenerateRepositoryAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static DtoModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var properties = typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .Select(p => (p.Name, p.Type.ToDisplayString()))
            .ToArray();
        return new DtoModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), properties);
    }

    private static void Execute(SourceProductionContext ctx, DtoModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Dtos;");
        sb.AppendLine();
        sb.AppendLine($"public sealed record {model.EntityName}Dto(");
        for (int i = 0; i < model.Properties.Length; i++)
        {
            var (name, type) = model.Properties[i];
            var comma = i < model.Properties.Length - 1 ? "," : "";
            sb.AppendLine($"    {type} {name}{comma}");
        }
        sb.AppendLine(");");

        ctx.AddSource($"{model.EntityName}Dto.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record DtoModel(string EntityName, string Namespace, (string Name, string Type)[] Properties);
}