using System.Text;

namespace VisionaryCoder.Generators.Dx;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class MappingGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.MapToAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static MappingModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[index: 0];
        var targetType = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "Unknown";
        return new MappingModel(SourceType: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString(), TargetType: targetType);
    }

    private static void Execute(SourceProductionContext ctx, MappingModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>Extension methods for mapping " + $"{model.SourceType} to {model.TargetType}</summary>");
        sb.AppendLine(value: "public static class " + $"{model.SourceType}MappingExtensions");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    public static object To{model.TargetType}(this {model.SourceType} source)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (source == null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine();
        sb.AppendLine(value: "        // TODO: Implement property-by-property mapping");
        sb.AppendLine(value: "        return new object();");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.SourceType}MappingExtensions.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record MappingModel(string SourceType, string Namespace, string TargetType);
}
