using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class MappingGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.MapToAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static MappingModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[0];
        var targetType = attr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "Unknown";
        return new MappingModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), targetType);
    }

    private static void Execute(SourceProductionContext ctx, MappingModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Extension methods for mapping " + $"{model.SourceType} to {model.TargetType}</summary>");
        sb.AppendLine("public static class " + $"{model.SourceType}MappingExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static object To{model.TargetType}(this {model.SourceType} source)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (source == null) throw new ArgumentNullException(nameof(source));");
        sb.AppendLine();
        sb.AppendLine("        // TODO: Implement property-by-property mapping");
        sb.AppendLine("        return new object();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.SourceType}MappingExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record MappingModel(string SourceType, string Namespace, string TargetType);
}
