using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class UnionGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.UnionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static UnionModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new UnionModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, UnionModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {model.UnionName}");
        sb.AppendLine("{");
        sb.AppendLine("    // Union case factory methods");
        sb.AppendLine($"    public static {model.UnionName} Success(object value) => new {model.UnionName} {{ /* TODO */ }};");
        sb.AppendLine($"    public static {model.UnionName} Failure(object error) => new {model.UnionName} {{ /* TODO */ }};");
        sb.AppendLine();
        sb.AppendLine("    // Pattern matching methods");
        sb.AppendLine("    public T Match<T>(Func<object, T> onSuccess, Func<object, T> onFailure) => throw new NotImplementedException();");
        sb.AppendLine();
        sb.AppendLine("    // Case properties");
        sb.AppendLine("    public bool IsSuccess { get; }");
        sb.AppendLine("    public bool IsFailure { get; }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.UnionName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record UnionModel(string UnionName, string Namespace);
}
