using System.Text;

namespace VisionaryCoder.Generators.Dx;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class UnionGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.UnionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static UnionModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new UnionModel(UnionName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, UnionModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: $"/// <summary>Auto-generated discriminated union type for <see cref=\"{{model.UnionName}}\"/>.</summary>");
        sb.AppendLine(value: $"public partial class {model.UnionName}");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    // Union case factory methods");
        sb.AppendLine(value: $"    public static {model.UnionName} Success(object value) => new {model.UnionName} {{ /* TODO */ }};");
        sb.AppendLine(value: $"    public static {model.UnionName} Failure(object error) => new {model.UnionName} {{ /* TODO */ }};");
        sb.AppendLine();
        sb.AppendLine(value: "    // Pattern matching methods");
        sb.AppendLine(value: "    public T Match<T>(Func<object, T> onSuccess, Func<object, T> onFailure) => throw new NotImplementedException();");
        sb.AppendLine();
        sb.AppendLine(value: "    // Case properties");
        sb.AppendLine(value: "    public bool IsSuccess { get; }");
        sb.AppendLine(value: "    public bool IsFailure { get; }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.UnionName}.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record UnionModel(string UnionName, string Namespace);
}
