using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ValidatorGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.GenerateValidatorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static ValidatorModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var attr = ctx.Attributes[0];
        var suffix = attr.NamedArguments.FirstOrDefault(a => a.Key == "ClassSuffix").Value.Value as string ?? "Validator";
        var useAnnotations = attr.NamedArguments.FirstOrDefault(a => a.Key == "UseDataAnnotations").Value.Value is not false;
        var properties = typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .Select(p => new PropertyModel(p.Name, p.Type.ToDisplayString(), p.IsRequired))
            .ToArray();
        return new ValidatorModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), suffix, useAnnotations, properties);
    }

    private static void Execute(SourceProductionContext ctx, ValidatorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Validators;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated validator for <see cref=\"{model.EntityName}\"/>.</summary>");
        sb.AppendLine($"public sealed class {model.EntityName}{model.Suffix}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Validates the provided instance and returns a result indicating success or failure.</summary>");
        sb.AppendLine($"    public ValidationResult Validate({model.EntityName} instance)");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new List<string>();");
        foreach (var prop in model.Properties)
        {
            if (prop.TypeName == "string" || prop.TypeName == "string?")
                sb.AppendLine($"        if (string.IsNullOrWhiteSpace(instance.{prop.Name})) errors.Add(\"\"{prop.Name} is required.\");");
        }
        sb.AppendLine("        return new ValidationResult(errors.Count == 0, errors);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EntityName}{model.Suffix}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record PropertyModel(string Name, string TypeName, bool IsRequired);
    private sealed record ValidatorModel(string EntityName, string Namespace, string Suffix, bool UseDataAnnotations, PropertyModel[] Properties);
}