using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class BuilderPatternGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.GenerateBuilderAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static BuilderModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new BuilderModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, BuilderModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {model.TypeName}Builder");
        sb.AppendLine("{");
        sb.AppendLine("    // TODO: Add property backing fields");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Fluent builder method</summary>");
        sb.AppendLine($"    public {model.TypeName}Builder WithProperty(object value)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Store value in backing field");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public {model.TypeName} Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Implement validation and construction");
        sb.AppendLine($"        return new {model.TypeName}();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    partial void Validate();");
        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}Builder.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record BuilderModel(string TypeName, string Namespace);
}
