using System.Text;

namespace VisionaryCoder.Generators.Design;

/// <summary>
/// Generates builder classes for fluent domain object construction.
/// Targets classes decorated with [VcBuilderAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class BuilderGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcBuilderAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static BuilderModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new BuilderModel(
            DomainObjectName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, BuilderModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Fluent builder for {model.DomainObjectName} domain object.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.DomainObjectName}Builder");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: $"    private {model.DomainObjectName}? _instance;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Initializes a new instance of the builder.</summary>");
        sb.AppendLine(value: $"    public {model.DomainObjectName}Builder()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: $"        _instance = new {model.DomainObjectName}();");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Creates a new builder instance for {model.DomainObjectName}.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    /// <returns>A new builder instance.</returns>");
        sb.AppendLine(value: $"    public static {model.DomainObjectName}Builder Create()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: $"        return new {model.DomainObjectName}Builder();");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Builds the {model.DomainObjectName} instance.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    /// <returns>The constructed {model.DomainObjectName} instance.</returns>");
        sb.AppendLine(value: $"    public {model.DomainObjectName} Build()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (_instance == null)");
        sb.AppendLine(value: $"            throw new InvalidOperationException(\"Cannot build {model.DomainObjectName}. Instance is null.\");");
        sb.AppendLine();
        sb.AppendLine(value: "        var result = _instance;");
        sb.AppendLine(value: "        _instance = null; // Clear to prevent reuse");
        sb.AppendLine(value: "        return result;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Resets the builder to a clean state.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    public {model.DomainObjectName}Builder Reset()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: $"        _instance = new {model.DomainObjectName}();");
        sb.AppendLine(value: "        return this;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.DomainObjectName}Builder.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record BuilderModel(string DomainObjectName, string Namespace);
}
