using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates builder classes for fluent domain object construction.
/// Targets classes decorated with [VcBuilderAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BuilderGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcBuilderAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static BuilderModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new BuilderModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, BuilderModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Fluent builder for {model.DomainObjectName} domain object.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.DomainObjectName}Builder");
        sb.AppendLine("{");
        sb.AppendLine($"    private {model.DomainObjectName}? _instance;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Initializes a new instance of the builder.</summary>");
        sb.AppendLine($"    public {model.DomainObjectName}Builder()");
        sb.AppendLine("    {");
        sb.AppendLine($"        _instance = new {model.DomainObjectName}();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Creates a new builder instance for {model.DomainObjectName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <returns>A new builder instance.</returns>");
        sb.AppendLine($"    public static {model.DomainObjectName}Builder Create()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {model.DomainObjectName}Builder();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Builds the {model.DomainObjectName} instance.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <returns>The constructed {model.DomainObjectName} instance.</returns>");
        sb.AppendLine($"    public {model.DomainObjectName} Build()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_instance == null)");
        sb.AppendLine($"            throw new InvalidOperationException(\"Cannot build {model.DomainObjectName}. Instance is null.\");");
        sb.AppendLine();
        sb.AppendLine("        var result = _instance;");
        sb.AppendLine("        _instance = null; // Clear to prevent reuse");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Resets the builder to a clean state.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public {model.DomainObjectName}Builder Reset()");
        sb.AppendLine("    {");
        sb.AppendLine($"        _instance = new {model.DomainObjectName}();");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.DomainObjectName}Builder.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record BuilderModel(string DomainObjectName, string Namespace);
}
