using System.Text;

namespace VisionaryCoder.Generators.Design;

[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class BuilderPatternGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "VisionaryCoder.Tooling.Shared.Attributes.GenerateBuilderAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static BuilderModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new BuilderModel(TypeName: typeSymbol.Name, Namespace: typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, BuilderModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine(value: $"public sealed class {model.TypeName}Builder");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    // TODO: Add property backing fields");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Fluent builder method</summary>");
        sb.AppendLine(value: $"    public {model.TypeName}Builder WithProperty(object value)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        // TODO: Store value in backing field");
        sb.AppendLine(value: "        return this;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: $"    public {model.TypeName} Build()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        // TODO: Implement validation and construction");
        sb.AppendLine(value: $"        return new {model.TypeName}();");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    partial void Validate();");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.TypeName}Builder.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record BuilderModel(string TypeName, string Namespace);
}
