using System.Text;

namespace VisionaryCoder.Generators.Design;

/// <summary>
/// Generates factory classes for domain object creation.
/// Targets interfaces decorated with [VcFactoryAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class FactoryGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcFactoryAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static FactoryModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new FactoryModel(
            FactoryName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, FactoryModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Factory implementation for creating domain objects.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {GetImplementationName(factoryName: model.FactoryName)} : {model.FactoryName}");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Creates a new domain object instance.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <returns>A new domain object instance.</returns>");
        sb.AppendLine(value: "    public object Create()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        // TODO: Implement factory creation logic");
        sb.AppendLine(value: "        return new object();");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Creates a new domain object instance asynchronously.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine(value: "    /// <returns>Task representing the asynchronous creation.</returns>");
        sb.AppendLine(value: "    public Task<object> CreateAsync(CancellationToken cancellationToken = default)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        var instance = Create();");
        sb.AppendLine(value: "        return Task.FromResult(instance);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Determines whether this factory can create instances.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <returns>True if the factory is capable of creating; false otherwise.</returns>");
        sb.AppendLine(value: "    public bool CanCreate()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return true;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{GetImplementationName(factoryName: model.FactoryName)}.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private static string GetImplementationName(string factoryName)
    {
        // If the interface starts with 'I', remove it; otherwise append 'Impl'
        return factoryName.StartsWith(value: "I") ? factoryName.Substring(startIndex: 1) : $"{factoryName}Impl";
    }

    private sealed record FactoryModel(string FactoryName, string Namespace);
}
