using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates factory classes for domain object creation.
/// Targets interfaces decorated with [VcFactoryAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FactoryGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcFactoryAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static FactoryModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new FactoryModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, FactoryModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Factory implementation for creating domain objects.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {GetImplementationName(model.FactoryName)} : {model.FactoryName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a new domain object instance.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <returns>A new domain object instance.</returns>");
        sb.AppendLine("    public object Create()");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Implement factory creation logic");
        sb.AppendLine("        return new object();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a new domain object instance asynchronously.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("    /// <returns>Task representing the asynchronous creation.</returns>");
        sb.AppendLine("    public Task<object> CreateAsync(CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var instance = Create();");
        sb.AppendLine("        return Task.FromResult(instance);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Determines whether this factory can create instances.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <returns>True if the factory is capable of creating; false otherwise.</returns>");
        sb.AppendLine("    public bool CanCreate()");
        sb.AppendLine("    {");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{GetImplementationName(model.FactoryName)}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetImplementationName(string factoryName)
    {
        // If the interface starts with 'I', remove it; otherwise append 'Impl'
        return factoryName.StartsWith("I") ? factoryName.Substring(1) : $"{factoryName}Impl";
    }

    private sealed record FactoryModel(string FactoryName, string Namespace);
}
