using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class OptionsPatternGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Dx.VcOptionsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static OptionsModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
        return new OptionsModel(typeSymbol.Name, ns);
    }

    private static void Execute(SourceProductionContext ctx, OptionsModel model)
    {
        var sectionName = model.TypeName.EndsWith("Options", StringComparison.Ordinal)
            ? model.TypeName[..^"Options".Length]
            : model.TypeName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Auto-generated options registration extensions for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public static class {model.TypeName}Extensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Registers <see cref=\"{model.TypeName}\"/> from the <paramref name=\"configuration\"/> section <c>\"{sectionName}\"</c>.</summary>");
        sb.AppendLine($"    public static IServiceCollection Add{sectionName}Options(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        IConfiguration configuration)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.Configure<{model.TypeName}>(configuration.GetSection(\"{sectionName}\"));");
        sb.AppendLine($"        services.AddSingleton<IValidateOptions<{model.TypeName}>, {model.TypeName}Validator>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated options validator stub for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"public sealed partial class {model.TypeName}Validator : IValidateOptions<{model.TypeName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public ValidateOptionsResult Validate(string? name, {model.TypeName} options)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Add validation logic for required fields");
        sb.AppendLine("        return ValidateOptionsResult.Success;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.TypeName}Extensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record OptionsModel(string TypeName, string Namespace);
}
