using System.Text;

namespace VisionaryCoder.Generators.Design;

/// <summary>
/// Generates polymorphic dispatcher classes for base type handling.
/// Targets classes decorated with [VcPolymorphicAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class PolymorphicGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcPolymorphicAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static PolymorphicModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new PolymorphicModel(
            BaseName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, PolymorphicModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Polymorphic dispatcher for {model.BaseName} type handling.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.BaseName}Dispatcher");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    private readonly Dictionary<Type, Func<object, object?>> _handlers = new();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Registers a handler for a specific derived type.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <typeparam name=\"TDerived\">The derived type.</typeparam>");
        sb.AppendLine(value: "    /// <param name=\"handler\">The handler function.</param>");
        sb.AppendLine(value: $"    public {model.BaseName}Dispatcher RegisterHandler<TDerived>(Func<TDerived, object?> handler)");
        sb.AppendLine(value: "        where TDerived : " + model.BaseName);
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (handler == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(handler), \"Handler cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine(value: "        _handlers[typeof(TDerived)] = obj => handler((TDerived)obj);");
        sb.AppendLine(value: "        return this;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Dispatches an instance to its registered handler.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    /// <param name=\"instance\">The {model.BaseName} instance.</param>");
        sb.AppendLine(value: "    /// <returns>The handler result, or null if no handler is registered.</returns>");
        sb.AppendLine(value: $"    public object? Dispatch({model.BaseName} instance)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (instance == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(instance), \"Instance cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine(value: "        var instanceType = instance.GetType();");
        sb.AppendLine(value: "        return _handlers.TryGetValue(instanceType, out var handler) ? handler(instance) : null;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Checks if a handler is registered for a derived type.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <typeparam name=\"TDerived\">The derived type.</typeparam>");
        sb.AppendLine(value: "    /// <returns>True if a handler exists; otherwise false.</returns>");
        sb.AppendLine(value: "    public bool HasHandler<TDerived>() where TDerived : " + model.BaseName);
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return _handlers.ContainsKey(typeof(TDerived));");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Clears all registered handlers.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public void ClearHandlers() => _handlers.Clear();");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.BaseName}Dispatcher.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record PolymorphicModel(string BaseName, string Namespace);
}
