using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates polymorphic dispatcher classes for base type handling.
/// Targets classes decorated with [VcPolymorphicAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PolymorphicGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcPolymorphicAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static PolymorphicModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new PolymorphicModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, PolymorphicModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Polymorphic dispatcher for {model.BaseName} type handling.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.BaseName}Dispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly Dictionary<Type, Func<object, object?>> _handlers = new();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers a handler for a specific derived type.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <typeparam name=\"TDerived\">The derived type.</typeparam>");
        sb.AppendLine("    /// <param name=\"handler\">The handler function.</param>");
        sb.AppendLine($"    public {model.BaseName}Dispatcher RegisterHandler<TDerived>(Func<TDerived, object?> handler)");
        sb.AppendLine("        where TDerived : " + model.BaseName);
        sb.AppendLine("    {");
        sb.AppendLine("        if (handler == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(handler), \"Handler cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine("        _handlers[typeof(TDerived)] = obj => handler((TDerived)obj);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Dispatches an instance to its registered handler.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"instance\">The {model.BaseName} instance.</param>");
        sb.AppendLine("    /// <returns>The handler result, or null if no handler is registered.</returns>");
        sb.AppendLine($"    public object? Dispatch({model.BaseName} instance)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (instance == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(instance), \"Instance cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine("        var instanceType = instance.GetType();");
        sb.AppendLine("        return _handlers.TryGetValue(instanceType, out var handler) ? handler(instance) : null;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Checks if a handler is registered for a derived type.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <typeparam name=\"TDerived\">The derived type.</typeparam>");
        sb.AppendLine("    /// <returns>True if a handler exists; otherwise false.</returns>");
        sb.AppendLine("    public bool HasHandler<TDerived>() where TDerived : " + model.BaseName);
        sb.AppendLine("    {");
        sb.AppendLine("        return _handlers.ContainsKey(typeof(TDerived));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Clears all registered handlers.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void ClearHandlers() => _handlers.Clear();");
        sb.AppendLine("}");

        ctx.AddSource($"{model.BaseName}Dispatcher.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record PolymorphicModel(string BaseName, string Namespace);
}
