using System.Text;

namespace VisionaryCoder.Generators.Design;

/// <summary>
/// Generates relay command classes for MVVM command binding.
/// Targets classes decorated with [VcRelayCommandAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class RelayCommandGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcRelayCommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static RelayCommandModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new RelayCommandModel(
            ViewModelName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, RelayCommandModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "using System.Windows.Input;");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Relay command for {model.ViewModelName} binding.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.ViewModelName}Command : ICommand");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    private readonly Action<object?> _execute;");
        sb.AppendLine(value: "    private readonly Predicate<object?>? _canExecute;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Raised when command execution state changes.</summary>");
        sb.AppendLine(value: "    public event EventHandler? CanExecuteChanged");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        add { CommandManager.RequerySuggested += value; }");
        sb.AppendLine(value: "        remove { CommandManager.RequerySuggested -= value; }");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Initializes a new relay command.</summary>");
        sb.AppendLine(value: $"    public {model.ViewModelName}Command(Action<object?> execute, Predicate<object?>? canExecute = null)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (execute == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(execute), \"Execute action cannot be null.\");");
        sb.AppendLine(value: "        _execute = execute;");
        sb.AppendLine(value: "        _canExecute = canExecute;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Determines whether the command can execute.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public bool CanExecute(object? parameter)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return _canExecute?.Invoke(parameter) ?? true;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Executes the command.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public void Execute(object? parameter)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (CanExecute(parameter))");
        sb.AppendLine(value: "            _execute(parameter);");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Raises CanExecuteChanged event.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public void RaiseCanExecuteChanged() => CommandManager.InvalidateRequerySuggested();");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.ViewModelName}Command.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record RelayCommandModel(string ViewModelName, string Namespace);
}
