using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates relay command classes for MVVM command binding.
/// Targets classes decorated with [VcRelayCommandAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RelayCommandGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcRelayCommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static RelayCommandModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new RelayCommandModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, RelayCommandModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("using System.Windows.Input;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Relay command for {model.ViewModelName} binding.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.ViewModelName}Command : ICommand");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly Action<object?> _execute;");
        sb.AppendLine("    private readonly Predicate<object?>? _canExecute;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Raised when command execution state changes.</summary>");
        sb.AppendLine("    public event EventHandler? CanExecuteChanged");
        sb.AppendLine("    {");
        sb.AppendLine("        add { CommandManager.RequerySuggested += value; }");
        sb.AppendLine("        remove { CommandManager.RequerySuggested -= value; }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Initializes a new relay command.</summary>");
        sb.AppendLine($"    public {model.ViewModelName}Command(Action<object?> execute, Predicate<object?>? canExecute = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (execute == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(execute), \"Execute action cannot be null.\");");
        sb.AppendLine("        _execute = execute;");
        sb.AppendLine("        _canExecute = canExecute;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Determines whether the command can execute.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool CanExecute(object? parameter)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _canExecute?.Invoke(parameter) ?? true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Executes the command.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void Execute(object? parameter)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (CanExecute(parameter))");
        sb.AppendLine("            _execute(parameter);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Raises CanExecuteChanged event.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void RaiseCanExecuteChanged() => CommandManager.InvalidateRequerySuggested();");
        sb.AppendLine("}");

        ctx.AddSource($"{model.ViewModelName}Command.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record RelayCommandModel(string ViewModelName, string Namespace);
}
