using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates specification classes for domain query criteria.
/// Targets classes decorated with [VcSpecificationAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SpecificationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcSpecificationAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static SpecificationModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new SpecificationModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, SpecificationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Base class for domain specifications.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public abstract class Specification<T>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets the criteria expression for filtering.</summary>");
        sb.AppendLine("    public virtual Func<T, bool>? Criteria { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the includes for eager loading.</summary>");
        sb.AppendLine("    public virtual List<string> Includes { get; } = new();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the order by expression.</summary>");
        sb.AppendLine("    public virtual Func<T, object>? OrderBy { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets a value indicating whether to order descending.</summary>");
        sb.AppendLine("    public virtual bool IsOrderByDescending { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the pagination page number.</summary>");
        sb.AppendLine("    public virtual int? PageNumber { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the pagination page size.</summary>");
        sb.AppendLine("    public virtual int? PageSize { get; }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Specification for {model.SpecName} domain object.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.SpecName}Specification : Specification<{model.SpecName}>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Initializes a new instance of the specification.</summary>");
        sb.AppendLine($"    public {model.SpecName}Specification()");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Initialize criteria, includes, and ordering as needed");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds an include path for eager loading.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"navigationPath\">The navigation property path.</param>");
        sb.AppendLine("    /// <returns>This specification for fluent API.</returns>");
        sb.AppendLine($"    public Specification<{model.SpecName}> AddInclude(string navigationPath)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!string.IsNullOrWhiteSpace(navigationPath))");
        sb.AppendLine("            Includes.Add(navigationPath);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.SpecName}Specification.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record SpecificationModel(string SpecName, string Namespace);
}
