using System.Text;

namespace VisionaryCoder.Generators.Design;

/// <summary>
/// Generates specification classes for domain query criteria.
/// Targets classes decorated with [VcSpecificationAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class SpecificationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcSpecificationAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static SpecificationModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new SpecificationModel(
            SpecName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, SpecificationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Base class for domain specifications.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public abstract class Specification<T>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Gets the criteria expression for filtering.</summary>");
        sb.AppendLine(value: "    public virtual Func<T, bool>? Criteria { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the includes for eager loading.</summary>");
        sb.AppendLine(value: "    public virtual List<string> Includes { get; } = new();");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the order by expression.</summary>");
        sb.AppendLine(value: "    public virtual Func<T, object>? OrderBy { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets a value indicating whether to order descending.</summary>");
        sb.AppendLine(value: "    public virtual bool IsOrderByDescending { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the pagination page number.</summary>");
        sb.AppendLine(value: "    public virtual int? PageNumber { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the pagination page size.</summary>");
        sb.AppendLine(value: "    public virtual int? PageSize { get; }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Specification for {model.SpecName} domain object.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.SpecName}Specification : Specification<{model.SpecName}>");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Initializes a new instance of the specification.</summary>");
        sb.AppendLine(value: $"    public {model.SpecName}Specification()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        // TODO: Initialize criteria, includes, and ordering as needed");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Adds an include path for eager loading.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"navigationPath\">The navigation property path.</param>");
        sb.AppendLine(value: "    /// <returns>This specification for fluent API.</returns>");
        sb.AppendLine(value: $"    public Specification<{model.SpecName}> AddInclude(string navigationPath)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (!string.IsNullOrWhiteSpace(navigationPath))");
        sb.AppendLine(value: "            Includes.Add(navigationPath);");
        sb.AppendLine(value: "        return this;");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.SpecName}Specification.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record SpecificationModel(string SpecName, string Namespace);
}
