using System.Text;

namespace VisionaryCoder.Generators.Design;

/// <summary>
/// Generates state machine classes implementing the state pattern.
/// Targets classes decorated with [VcStatePatternAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class StatePatternGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcStatePatternAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static StatePatternModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new StatePatternModel(
            EntityName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, StatePatternModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// State machine for {model.EntityName} with state pattern implementation.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.EntityName}StateMachine");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    private IState _currentState;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the current state.</summary>");
        sb.AppendLine(value: "    public IState CurrentState => _currentState;");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Initializes a new state machine with an initial state.</summary>");
        sb.AppendLine(value: $"    public {model.EntityName}StateMachine(IState initialState)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (initialState == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(initialState), \"Initial state cannot be null.\");");
        sb.AppendLine(value: "        _currentState = initialState;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Transitions to a new state.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"newState\">The new state to transition to.</param>");
        sb.AppendLine(value: "    public void TransitionTo(IState newState)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (newState == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(newState), \"New state cannot be null.\");");
        sb.AppendLine(value: "        _currentState = newState;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Executes the current state's action.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <returns>The state action result.</returns>");
        sb.AppendLine(value: "    public string Execute()");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        return _currentState?.Execute() ?? \"No state\";");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Resets the state machine to the initial state.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    /// <param name=\"initialState\">The initial state to reset to.</param>");
        sb.AppendLine(value: "    public void Reset(IState initialState)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (initialState == null)");
        sb.AppendLine(value: "            throw new ArgumentNullException(nameof(initialState), \"Initial state cannot be null.\");");
        sb.AppendLine(value: "        _currentState = initialState;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: "    /// Represents a state in the state machine.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: "    public interface IState");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        /// <summary>Executes the state action.</summary>");
        sb.AppendLine(value: "        string Execute();");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.EntityName}StateMachine.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record StatePatternModel(string EntityName, string Namespace);
}
