using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates state machine classes implementing the state pattern.
/// Targets classes decorated with [VcStatePatternAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class StatePatternGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcStatePatternAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static StatePatternModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new StatePatternModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, StatePatternModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// State machine for {model.EntityName} with state pattern implementation.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.EntityName}StateMachine");
        sb.AppendLine("{");
        sb.AppendLine("    private IState _currentState;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the current state.</summary>");
        sb.AppendLine("    public IState CurrentState => _currentState;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Initializes a new state machine with an initial state.</summary>");
        sb.AppendLine($"    public {model.EntityName}StateMachine(IState initialState)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (initialState == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(initialState), \"Initial state cannot be null.\");");
        sb.AppendLine("        _currentState = initialState;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Transitions to a new state.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"newState\">The new state to transition to.</param>");
        sb.AppendLine("    public void TransitionTo(IState newState)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (newState == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(newState), \"New state cannot be null.\");");
        sb.AppendLine("        _currentState = newState;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Executes the current state's action.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <returns>The state action result.</returns>");
        sb.AppendLine("    public string Execute()");
        sb.AppendLine("    {");
        sb.AppendLine("        return _currentState?.Execute() ?? \"No state\";");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Resets the state machine to the initial state.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"initialState\">The initial state to reset to.</param>");
        sb.AppendLine("    public void Reset(IState initialState)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (initialState == null)");
        sb.AppendLine("            throw new ArgumentNullException(nameof(initialState), \"Initial state cannot be null.\");");
        sb.AppendLine("        _currentState = initialState;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Represents a state in the state machine.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public interface IState");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Executes the state action.</summary>");
        sb.AppendLine("        string Execute();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.EntityName}StateMachine.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record StatePatternModel(string EntityName, string Namespace);
}
