using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ValidationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "System.ComponentModel.DataAnnotations.RequiredAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static ValidationModel? GetModel(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not ClassDeclarationSyntax classDecl) return null;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol typeSymbol) return null;
        return new ValidationModel(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(SourceProductionContext ctx, ValidationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}.Validators;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {model.TypeName}Validator");
        sb.AppendLine("{");
        sb.AppendLine($"    public ValidationResult Validate({model.TypeName} instance)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (instance == null)");
        sb.AppendLine("            return new ValidationResult(false, \"Instance cannot be null\");");
        sb.AppendLine();
        sb.AppendLine("        // TODO: Add property validation rules");
        sb.AppendLine("        return new ValidationResult(true, null);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public sealed record ValidationResult(bool IsValid, string? ErrorMessage);");

        ctx.AddSource($"{model.TypeName}Validator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record ValidationModel(string TypeName, string Namespace);
}
