using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VisionaryCoder.Tooling.Generators;

/// <summary>
/// Generates validator classes for validating domain objects.
/// Targets classes decorated with [VcValidatorAttribute].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ValidationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcValidatorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(provider, Execute);
    }

    private static ValidationModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new ValidationModel(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, ValidationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Validator for {model.DomainObjectName} domain object.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {model.DomainObjectName}Validator");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Validates a {model.DomainObjectName} object.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"target\">The object to validate.</param>");
        sb.AppendLine("    /// <returns>A validation result containing any errors.</returns>");
        sb.AppendLine($"    public ValidationResult Validate({model.DomainObjectName} target)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (target == null)");
        sb.AppendLine("            return ValidationResult.Failure(\"Target object cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine("        var errors = new List<string>();");
        sb.AppendLine();
        sb.AppendLine("        // TODO: Add validation rules");
        sb.AppendLine();
        sb.AppendLine("        return errors.Any()");
        sb.AppendLine("            ? ValidationResult.Failure(errors)");
        sb.AppendLine("            : ValidationResult.Success();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Asynchronously validates a {model.DomainObjectName} object.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"target\">The object to validate.</param>");
        sb.AppendLine("    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine("    /// <returns>Task representing the asynchronous validation.</returns>");
        sb.AppendLine($"    public Task<ValidationResult> ValidateAsync({model.DomainObjectName} target, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var result = Validate(target);");
        sb.AppendLine("        return Task.FromResult(result);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Validation result containing success status and error messages.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class ValidationResult");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets a value indicating whether validation succeeded.</summary>");
        sb.AppendLine("    public bool IsValid { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Gets the validation error messages.</summary>");
        sb.AppendLine("    public IReadOnlyList<string> Errors { get; }");
        sb.AppendLine();
        sb.AppendLine("    private ValidationResult(bool isValid, IReadOnlyList<string> errors)");
        sb.AppendLine("    {");
        sb.AppendLine("        IsValid = isValid;");
        sb.AppendLine("        Errors = errors;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a successful validation result.</summary>");
        sb.AppendLine("    public static ValidationResult Success() => new(true, Array.Empty<string>());");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a failed validation result with a single error.</summary>");
        sb.AppendLine("    public static ValidationResult Failure(string error) => new(false, new[] { error });");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Creates a failed validation result with multiple errors.</summary>");
        sb.AppendLine("    public static ValidationResult Failure(IEnumerable<string> errors) => new(false, errors.ToList().AsReadOnly());");
        sb.AppendLine("}");

        ctx.AddSource($"{model.DomainObjectName}Validator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record ValidationModel(string DomainObjectName, string Namespace);
}
