using System.Text;

namespace VisionaryCoder.Generators.Design;

/// <summary>
/// Generates validator classes for validating domain objects.
/// Targets classes decorated with [VcValidatorAttribute].
/// </summary>
[Generator(firstLanguage: LanguageNames.CSharp)]
public sealed class ValidationGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Vc.Generators.Abstractions.Design.VcValidatorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx: ctx))
            .Where(predicate: static m => m is not null)
            .Select(selector: static (m, _) => m!);

        context.RegisterSourceOutput(source: provider, action: Execute);
    }

    private static ValidationModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;
        return new ValidationModel(
            DomainObjectName: typeSymbol.Name,
            Namespace: typeSymbol.ContainingNamespace.ToDisplayString()
        );
    }

    private static void Execute(SourceProductionContext ctx, ValidationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine(value: "// <auto-generated by VisionaryCoder.Tooling.Generators />");
        sb.AppendLine(value: "#nullable enable");
        sb.AppendLine();
        sb.AppendLine(value: $"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: $"/// Validator for {model.DomainObjectName} domain object.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: $"public sealed partial class {model.DomainObjectName}Validator");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Validates a {model.DomainObjectName} object.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    /// <param name=\"target\">The object to validate.</param>");
        sb.AppendLine(value: "    /// <returns>A validation result containing any errors.</returns>");
        sb.AppendLine(value: $"    public ValidationResult Validate({model.DomainObjectName} target)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        if (target == null)");
        sb.AppendLine(value: "            return ValidationResult.Failure(\"Target object cannot be null.\");");
        sb.AppendLine();
        sb.AppendLine(value: "        var errors = new List<string>();");
        sb.AppendLine();
        sb.AppendLine(value: "        // TODO: Add validation rules");
        sb.AppendLine();
        sb.AppendLine(value: "        return errors.Any()");
        sb.AppendLine(value: "            ? ValidationResult.Failure(errors)");
        sb.AppendLine(value: "            : ValidationResult.Success();");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>");
        sb.AppendLine(value: $"    /// Asynchronously validates a {model.DomainObjectName} object.");
        sb.AppendLine(value: "    /// </summary>");
        sb.AppendLine(value: $"    /// <param name=\"target\">The object to validate.</param>");
        sb.AppendLine(value: "    /// <param name=\"cancellationToken\">Cancellation token.</param>");
        sb.AppendLine(value: "    /// <returns>Task representing the asynchronous validation.</returns>");
        sb.AppendLine(value: $"    public Task<ValidationResult> ValidateAsync({model.DomainObjectName} target, CancellationToken cancellationToken = default)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        var result = Validate(target);");
        sb.AppendLine(value: "        return Task.FromResult(result);");
        sb.AppendLine(value: "    }");
        sb.AppendLine(value: "}");
        sb.AppendLine();
        sb.AppendLine(value: "/// <summary>");
        sb.AppendLine(value: "/// Validation result containing success status and error messages.");
        sb.AppendLine(value: "/// </summary>");
        sb.AppendLine(value: "public sealed class ValidationResult");
        sb.AppendLine(value: "{");
        sb.AppendLine(value: "    /// <summary>Gets a value indicating whether validation succeeded.</summary>");
        sb.AppendLine(value: "    public bool IsValid { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Gets the validation error messages.</summary>");
        sb.AppendLine(value: "    public IReadOnlyList<string> Errors { get; }");
        sb.AppendLine();
        sb.AppendLine(value: "    private ValidationResult(bool isValid, IReadOnlyList<string> errors)");
        sb.AppendLine(value: "    {");
        sb.AppendLine(value: "        IsValid = isValid;");
        sb.AppendLine(value: "        Errors = errors;");
        sb.AppendLine(value: "    }");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Creates a successful validation result.</summary>");
        sb.AppendLine(value: "    public static ValidationResult Success() => new(true, Array.Empty<string>());");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Creates a failed validation result with a single error.</summary>");
        sb.AppendLine(value: "    public static ValidationResult Failure(string error) => new(false, new[] { error });");
        sb.AppendLine();
        sb.AppendLine(value: "    /// <summary>Creates a failed validation result with multiple errors.</summary>");
        sb.AppendLine(value: "    public static ValidationResult Failure(IEnumerable<string> errors) => new(false, errors.ToList().AsReadOnly());");
        sb.AppendLine(value: "}");

        ctx.AddSource(hintName: $"{model.DomainObjectName}Validator.g.cs", sourceText: SourceText.From(text: sb.ToString(), encoding: Encoding.UTF8));
    }

    private sealed record ValidationModel(string DomainObjectName, string Namespace);
}
